/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AuditLog
 */
@JsonPropertyOrder({
  AuditLog.JSON_PROPERTY_WEEK_NUMBER,
  AuditLog.JSON_PROPERTY_MODIFIED_PROGRAM_ID,
  AuditLog.JSON_PROPERTY_MODIFIED_TIMESTAMP,
  AuditLog.JSON_PROPERTY_MODIFIED_COMPANY_CODE,
  AuditLog.JSON_PROPERTY_MODIFIED_USER_ID,
  AuditLog.JSON_PROPERTY_CREATED_PROGRAM_ID,
  AuditLog.JSON_PROPERTY_CREATED_TIMESTAMP,
  AuditLog.JSON_PROPERTY_CREATED_COMPANY_CODE,
  AuditLog.JSON_PROPERTY_CREATED_USER_ID,
  AuditLog.JSON_PROPERTY_MESSAGE_ID
})
@JsonTypeName("auditLog")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class AuditLog {
  public static final String JSON_PROPERTY_WEEK_NUMBER = "weekNumber";
  private String weekNumber;

  public static final String JSON_PROPERTY_MODIFIED_PROGRAM_ID = "modifiedProgramId";
  private String modifiedProgramId;

  public static final String JSON_PROPERTY_MODIFIED_TIMESTAMP = "modifiedTimestamp";
  private String modifiedTimestamp;

  public static final String JSON_PROPERTY_MODIFIED_COMPANY_CODE = "modifiedCompanyCode";
  private String modifiedCompanyCode;

  public static final String JSON_PROPERTY_MODIFIED_USER_ID = "modifiedUserId";
  private String modifiedUserId;

  public static final String JSON_PROPERTY_CREATED_PROGRAM_ID = "createdProgramId";
  private String createdProgramId;

  public static final String JSON_PROPERTY_CREATED_TIMESTAMP = "createdTimestamp";
  private String createdTimestamp;

  public static final String JSON_PROPERTY_CREATED_COMPANY_CODE = "createdCompanyCode";
  private String createdCompanyCode;

  public static final String JSON_PROPERTY_CREATED_USER_ID = "createdUserId";
  private String createdUserId;

  public static final String JSON_PROPERTY_MESSAGE_ID = "messageId";
  private String messageId;


  public AuditLog weekNumber(String weekNumber) {
    
    this.weekNumber = weekNumber;
    return this;
  }

   /**
   * Get weekNumber
   * @return weekNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WEEK_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWeekNumber() {
    return weekNumber;
  }


  public void setWeekNumber(String weekNumber) {
    this.weekNumber = weekNumber;
  }


  public AuditLog modifiedProgramId(String modifiedProgramId) {
    
    this.modifiedProgramId = modifiedProgramId;
    return this;
  }

   /**
   * Get modifiedProgramId
   * @return modifiedProgramId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MODIFIED_PROGRAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModifiedProgramId() {
    return modifiedProgramId;
  }


  public void setModifiedProgramId(String modifiedProgramId) {
    this.modifiedProgramId = modifiedProgramId;
  }


  public AuditLog modifiedTimestamp(String modifiedTimestamp) {
    
    this.modifiedTimestamp = modifiedTimestamp;
    return this;
  }

   /**
   * Get modifiedTimestamp
   * @return modifiedTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MODIFIED_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModifiedTimestamp() {
    return modifiedTimestamp;
  }


  public void setModifiedTimestamp(String modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
  }


  public AuditLog modifiedCompanyCode(String modifiedCompanyCode) {
    
    this.modifiedCompanyCode = modifiedCompanyCode;
    return this;
  }

   /**
   * Get modifiedCompanyCode
   * @return modifiedCompanyCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MODIFIED_COMPANY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModifiedCompanyCode() {
    return modifiedCompanyCode;
  }


  public void setModifiedCompanyCode(String modifiedCompanyCode) {
    this.modifiedCompanyCode = modifiedCompanyCode;
  }


  public AuditLog modifiedUserId(String modifiedUserId) {
    
    this.modifiedUserId = modifiedUserId;
    return this;
  }

   /**
   * Get modifiedUserId
   * @return modifiedUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MODIFIED_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModifiedUserId() {
    return modifiedUserId;
  }


  public void setModifiedUserId(String modifiedUserId) {
    this.modifiedUserId = modifiedUserId;
  }


  public AuditLog createdProgramId(String createdProgramId) {
    
    this.createdProgramId = createdProgramId;
    return this;
  }

   /**
   * Get createdProgramId
   * @return createdProgramId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_PROGRAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedProgramId() {
    return createdProgramId;
  }


  public void setCreatedProgramId(String createdProgramId) {
    this.createdProgramId = createdProgramId;
  }


  public AuditLog createdTimestamp(String createdTimestamp) {
    
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * Get createdTimestamp
   * @return createdTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedTimestamp() {
    return createdTimestamp;
  }


  public void setCreatedTimestamp(String createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public AuditLog createdCompanyCode(String createdCompanyCode) {
    
    this.createdCompanyCode = createdCompanyCode;
    return this;
  }

   /**
   * Get createdCompanyCode
   * @return createdCompanyCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_COMPANY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedCompanyCode() {
    return createdCompanyCode;
  }


  public void setCreatedCompanyCode(String createdCompanyCode) {
    this.createdCompanyCode = createdCompanyCode;
  }


  public AuditLog createdUserId(String createdUserId) {
    
    this.createdUserId = createdUserId;
    return this;
  }

   /**
   * Get createdUserId
   * @return createdUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedUserId() {
    return createdUserId;
  }


  public void setCreatedUserId(String createdUserId) {
    this.createdUserId = createdUserId;
  }


  public AuditLog messageId(String messageId) {
    
    this.messageId = messageId;
    return this;
  }

   /**
   * Get messageId
   * @return messageId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MESSAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessageId() {
    return messageId;
  }


  public void setMessageId(String messageId) {
    this.messageId = messageId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditLog auditLog = (AuditLog) o;
    return Objects.equals(this.weekNumber, auditLog.weekNumber) &&
        Objects.equals(this.modifiedProgramId, auditLog.modifiedProgramId) &&
        Objects.equals(this.modifiedTimestamp, auditLog.modifiedTimestamp) &&
        Objects.equals(this.modifiedCompanyCode, auditLog.modifiedCompanyCode) &&
        Objects.equals(this.modifiedUserId, auditLog.modifiedUserId) &&
        Objects.equals(this.createdProgramId, auditLog.createdProgramId) &&
        Objects.equals(this.createdTimestamp, auditLog.createdTimestamp) &&
        Objects.equals(this.createdCompanyCode, auditLog.createdCompanyCode) &&
        Objects.equals(this.createdUserId, auditLog.createdUserId) &&
        Objects.equals(this.messageId, auditLog.messageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weekNumber, modifiedProgramId, modifiedTimestamp, modifiedCompanyCode, modifiedUserId, createdProgramId, createdTimestamp, createdCompanyCode, createdUserId, messageId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditLog {\n");
    sb.append("    weekNumber: ").append(toIndentedString(weekNumber)).append("\n");
    sb.append("    modifiedProgramId: ").append(toIndentedString(modifiedProgramId)).append("\n");
    sb.append("    modifiedTimestamp: ").append(toIndentedString(modifiedTimestamp)).append("\n");
    sb.append("    modifiedCompanyCode: ").append(toIndentedString(modifiedCompanyCode)).append("\n");
    sb.append("    modifiedUserId: ").append(toIndentedString(modifiedUserId)).append("\n");
    sb.append("    createdProgramId: ").append(toIndentedString(createdProgramId)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    createdCompanyCode: ").append(toIndentedString(createdCompanyCode)).append("\n");
    sb.append("    createdUserId: ").append(toIndentedString(createdUserId)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

