/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CashOnDelivery
 */
@JsonPropertyOrder({
  CashOnDelivery.JSON_PROPERTY_GOODS_DESCRIPTION,
  CashOnDelivery.JSON_PROPERTY_AMOUNT,
  CashOnDelivery.JSON_PROPERTY_AMOUNT_CURRENCY,
  CashOnDelivery.JSON_PROPERTY_CONTROL_IDENTIFICATION_NUMBER,
  CashOnDelivery.JSON_PROPERTY_ACCOUNT_NUMBER,
  CashOnDelivery.JSON_PROPERTY_AMOUNT_CHECK_DIGIT,
  CashOnDelivery.JSON_PROPERTY_ACCOUNT_TYPE,
  CashOnDelivery.JSON_PROPERTY_CREATED_PROGRAM_ID,
  CashOnDelivery.JSON_PROPERTY_CREATED_TIMESTAMP,
  CashOnDelivery.JSON_PROPERTY_MODIFIED_PROGRAM_ID,
  CashOnDelivery.JSON_PROPERTY_MODIFIED_TIMESTAMP
})
@JsonTypeName("cashOnDelivery")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class CashOnDelivery {
  public static final String JSON_PROPERTY_GOODS_DESCRIPTION = "goodsDescription";
  private String goodsDescription;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private BigDecimal amount;

  public static final String JSON_PROPERTY_AMOUNT_CURRENCY = "amountCurrency";
  private String amountCurrency;

  public static final String JSON_PROPERTY_CONTROL_IDENTIFICATION_NUMBER = "controlIdentificationNumber";
  private String controlIdentificationNumber;

  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "accountNumber";
  private String accountNumber;

  public static final String JSON_PROPERTY_AMOUNT_CHECK_DIGIT = "amountCheckDigit";
  private String amountCheckDigit;

  public static final String JSON_PROPERTY_ACCOUNT_TYPE = "accountType";
  private String accountType;

  public static final String JSON_PROPERTY_CREATED_PROGRAM_ID = "createdProgramId";
  private String createdProgramId;

  public static final String JSON_PROPERTY_CREATED_TIMESTAMP = "createdTimestamp";
  private OffsetDateTime createdTimestamp;

  public static final String JSON_PROPERTY_MODIFIED_PROGRAM_ID = "modifiedProgramId";
  private String modifiedProgramId;

  public static final String JSON_PROPERTY_MODIFIED_TIMESTAMP = "modifiedTimestamp";
  private OffsetDateTime modifiedTimestamp;


  public CashOnDelivery goodsDescription(String goodsDescription) {
    
    this.goodsDescription = goodsDescription;
    return this;
  }

   /**
   * Get goodsDescription
   * @return goodsDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GOODS_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGoodsDescription() {
    return goodsDescription;
  }


  public void setGoodsDescription(String goodsDescription) {
    this.goodsDescription = goodsDescription;
  }


  public CashOnDelivery amount(BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getAmount() {
    return amount;
  }


  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }


  public CashOnDelivery amountCurrency(String amountCurrency) {
    
    this.amountCurrency = amountCurrency;
    return this;
  }

   /**
   * Get amountCurrency
   * @return amountCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAmountCurrency() {
    return amountCurrency;
  }


  public void setAmountCurrency(String amountCurrency) {
    this.amountCurrency = amountCurrency;
  }


  public CashOnDelivery controlIdentificationNumber(String controlIdentificationNumber) {
    
    this.controlIdentificationNumber = controlIdentificationNumber;
    return this;
  }

   /**
   * Get controlIdentificationNumber
   * @return controlIdentificationNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTROL_IDENTIFICATION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getControlIdentificationNumber() {
    return controlIdentificationNumber;
  }


  public void setControlIdentificationNumber(String controlIdentificationNumber) {
    this.controlIdentificationNumber = controlIdentificationNumber;
  }


  public CashOnDelivery accountNumber(String accountNumber) {
    
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountNumber() {
    return accountNumber;
  }


  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public CashOnDelivery amountCheckDigit(String amountCheckDigit) {
    
    this.amountCheckDigit = amountCheckDigit;
    return this;
  }

   /**
   * Get amountCheckDigit
   * @return amountCheckDigit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT_CHECK_DIGIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAmountCheckDigit() {
    return amountCheckDigit;
  }


  public void setAmountCheckDigit(String amountCheckDigit) {
    this.amountCheckDigit = amountCheckDigit;
  }


  public CashOnDelivery accountType(String accountType) {
    
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountType() {
    return accountType;
  }


  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }


  public CashOnDelivery createdProgramId(String createdProgramId) {
    
    this.createdProgramId = createdProgramId;
    return this;
  }

   /**
   * Get createdProgramId
   * @return createdProgramId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_PROGRAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedProgramId() {
    return createdProgramId;
  }


  public void setCreatedProgramId(String createdProgramId) {
    this.createdProgramId = createdProgramId;
  }


  public CashOnDelivery createdTimestamp(OffsetDateTime createdTimestamp) {
    
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * Get createdTimestamp
   * @return createdTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedTimestamp() {
    return createdTimestamp;
  }


  public void setCreatedTimestamp(OffsetDateTime createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public CashOnDelivery modifiedProgramId(String modifiedProgramId) {
    
    this.modifiedProgramId = modifiedProgramId;
    return this;
  }

   /**
   * Get modifiedProgramId
   * @return modifiedProgramId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MODIFIED_PROGRAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModifiedProgramId() {
    return modifiedProgramId;
  }


  public void setModifiedProgramId(String modifiedProgramId) {
    this.modifiedProgramId = modifiedProgramId;
  }


  public CashOnDelivery modifiedTimestamp(OffsetDateTime modifiedTimestamp) {
    
    this.modifiedTimestamp = modifiedTimestamp;
    return this;
  }

   /**
   * Get modifiedTimestamp
   * @return modifiedTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MODIFIED_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getModifiedTimestamp() {
    return modifiedTimestamp;
  }


  public void setModifiedTimestamp(OffsetDateTime modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashOnDelivery cashOnDelivery = (CashOnDelivery) o;
    return Objects.equals(this.goodsDescription, cashOnDelivery.goodsDescription) &&
        Objects.equals(this.amount, cashOnDelivery.amount) &&
        Objects.equals(this.amountCurrency, cashOnDelivery.amountCurrency) &&
        Objects.equals(this.controlIdentificationNumber, cashOnDelivery.controlIdentificationNumber) &&
        Objects.equals(this.accountNumber, cashOnDelivery.accountNumber) &&
        Objects.equals(this.amountCheckDigit, cashOnDelivery.amountCheckDigit) &&
        Objects.equals(this.accountType, cashOnDelivery.accountType) &&
        Objects.equals(this.createdProgramId, cashOnDelivery.createdProgramId) &&
        Objects.equals(this.createdTimestamp, cashOnDelivery.createdTimestamp) &&
        Objects.equals(this.modifiedProgramId, cashOnDelivery.modifiedProgramId) &&
        Objects.equals(this.modifiedTimestamp, cashOnDelivery.modifiedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(goodsDescription, amount, amountCurrency, controlIdentificationNumber, accountNumber, amountCheckDigit, accountType, createdProgramId, createdTimestamp, modifiedProgramId, modifiedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CashOnDelivery {\n");
    sb.append("    goodsDescription: ").append(toIndentedString(goodsDescription)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    amountCurrency: ").append(toIndentedString(amountCurrency)).append("\n");
    sb.append("    controlIdentificationNumber: ").append(toIndentedString(controlIdentificationNumber)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    amountCheckDigit: ").append(toIndentedString(amountCheckDigit)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    createdProgramId: ").append(toIndentedString(createdProgramId)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    modifiedProgramId: ").append(toIndentedString(modifiedProgramId)).append("\n");
    sb.append("    modifiedTimestamp: ").append(toIndentedString(modifiedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

