/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Charges
 */
@JsonPropertyOrder({
  Charges.JSON_PROPERTY_CHARGE_TYPE,
  Charges.JSON_PROPERTY_CHARGE_CODE,
  Charges.JSON_PROPERTY_NET_AMOUNT,
  Charges.JSON_PROPERTY_NET_CURRENCY,
  Charges.JSON_PROPERTY_GROSS_AMOUNT,
  Charges.JSON_PROPERTY_GROSS_CURRENCY
})
@JsonTypeName("charges")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class Charges {
  public static final String JSON_PROPERTY_CHARGE_TYPE = "chargeType";
  private String chargeType;

  public static final String JSON_PROPERTY_CHARGE_CODE = "chargeCode";
  private String chargeCode;

  public static final String JSON_PROPERTY_NET_AMOUNT = "netAmount";
  private BigDecimal netAmount;

  public static final String JSON_PROPERTY_NET_CURRENCY = "netCurrency";
  private String netCurrency;

  public static final String JSON_PROPERTY_GROSS_AMOUNT = "grossAmount";
  private BigDecimal grossAmount;

  public static final String JSON_PROPERTY_GROSS_CURRENCY = "grossCurrency";
  private String grossCurrency;


  public Charges chargeType(String chargeType) {
    
    this.chargeType = chargeType;
    return this;
  }

   /**
   * Get chargeType
   * @return chargeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHARGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChargeType() {
    return chargeType;
  }


  public void setChargeType(String chargeType) {
    this.chargeType = chargeType;
  }


  public Charges chargeCode(String chargeCode) {
    
    this.chargeCode = chargeCode;
    return this;
  }

   /**
   * Get chargeCode
   * @return chargeCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHARGE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChargeCode() {
    return chargeCode;
  }


  public void setChargeCode(String chargeCode) {
    this.chargeCode = chargeCode;
  }


  public Charges netAmount(BigDecimal netAmount) {
    
    this.netAmount = netAmount;
    return this;
  }

   /**
   * Get netAmount
   * @return netAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NET_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getNetAmount() {
    return netAmount;
  }


  public void setNetAmount(BigDecimal netAmount) {
    this.netAmount = netAmount;
  }


  public Charges netCurrency(String netCurrency) {
    
    this.netCurrency = netCurrency;
    return this;
  }

   /**
   * Get netCurrency
   * @return netCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NET_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNetCurrency() {
    return netCurrency;
  }


  public void setNetCurrency(String netCurrency) {
    this.netCurrency = netCurrency;
  }


  public Charges grossAmount(BigDecimal grossAmount) {
    
    this.grossAmount = grossAmount;
    return this;
  }

   /**
   * Get grossAmount
   * @return grossAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GROSS_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getGrossAmount() {
    return grossAmount;
  }


  public void setGrossAmount(BigDecimal grossAmount) {
    this.grossAmount = grossAmount;
  }


  public Charges grossCurrency(String grossCurrency) {
    
    this.grossCurrency = grossCurrency;
    return this;
  }

   /**
   * Get grossCurrency
   * @return grossCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GROSS_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGrossCurrency() {
    return grossCurrency;
  }


  public void setGrossCurrency(String grossCurrency) {
    this.grossCurrency = grossCurrency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Charges charges = (Charges) o;
    return Objects.equals(this.chargeType, charges.chargeType) &&
        Objects.equals(this.chargeCode, charges.chargeCode) &&
        Objects.equals(this.netAmount, charges.netAmount) &&
        Objects.equals(this.netCurrency, charges.netCurrency) &&
        Objects.equals(this.grossAmount, charges.grossAmount) &&
        Objects.equals(this.grossCurrency, charges.grossCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chargeType, chargeCode, netAmount, netCurrency, grossAmount, grossCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Charges {\n");
    sb.append("    chargeType: ").append(toIndentedString(chargeType)).append("\n");
    sb.append("    chargeCode: ").append(toIndentedString(chargeCode)).append("\n");
    sb.append("    netAmount: ").append(toIndentedString(netAmount)).append("\n");
    sb.append("    netCurrency: ").append(toIndentedString(netCurrency)).append("\n");
    sb.append("    grossAmount: ").append(toIndentedString(grossAmount)).append("\n");
    sb.append("    grossCurrency: ").append(toIndentedString(grossCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

