/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import no.posten.ph.consignment.model.Attributes;
import no.posten.ph.consignment.model.AuditLog;
import no.posten.ph.consignment.model.Coordinates;
import no.posten.ph.consignment.model.DeliveryDetails;
import no.posten.ph.consignment.model.Images;
import no.posten.ph.consignment.model.RbtInformation;
import no.posten.ph.consignment.model.Signature;
import no.posten.ph.consignment.model.WeightVolTemp;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ConsignmentEvent
 */
@JsonPropertyOrder({
  ConsignmentEvent.JSON_PROPERTY_CONSIGNMENT_NO,
  ConsignmentEvent.JSON_PROPERTY_EVENT_DATE,
  ConsignmentEvent.JSON_PROPERTY_EVENT_TIME,
  ConsignmentEvent.JSON_PROPERTY_EVENT_CODE,
  ConsignmentEvent.JSON_PROPERTY_ACTION_CODE,
  ConsignmentEvent.JSON_PROPERTY_REASON_CODE,
  ConsignmentEvent.JSON_PROPERTY_UNIT_CODE,
  ConsignmentEvent.JSON_PROPERTY_POST_CODE,
  ConsignmentEvent.JSON_PROPERTY_COUNTRY_CODE,
  ConsignmentEvent.JSON_PROPERTY_COMPANY_CODE,
  ConsignmentEvent.JSON_PROPERTY_CONSIGNMENT_NO_SOURCE,
  ConsignmentEvent.JSON_PROPERTY_STATUS,
  ConsignmentEvent.JSON_PROPERTY_SYSTEM_CODE,
  ConsignmentEvent.JSON_PROPERTY_SOURCE_SYSTEM,
  ConsignmentEvent.JSON_PROPERTY_EQUIPMENT_TYPE,
  ConsignmentEvent.JSON_PROPERTY_EQUIPMENT_ID,
  ConsignmentEvent.JSON_PROPERTY_EQUIPMENT_MSG_COUNTER,
  ConsignmentEvent.JSON_PROPERTY_POST_REFERENCE,
  ConsignmentEvent.JSON_PROPERTY_HANDED_OVER_TO_UNIT,
  ConsignmentEvent.JSON_PROPERTY_SHELF_CODE,
  ConsignmentEvent.JSON_PROPERTY_PICK_UP_CODE,
  ConsignmentEvent.JSON_PROPERTY_RETURN_DATE,
  ConsignmentEvent.JSON_PROPERTY_COMMENTS,
  ConsignmentEvent.JSON_PROPERTY_DELIVERY_DETAILS,
  ConsignmentEvent.JSON_PROPERTY_SIGNATURE,
  ConsignmentEvent.JSON_PROPERTY_IMAGES,
  ConsignmentEvent.JSON_PROPERTY_RBT_INFORMATION,
  ConsignmentEvent.JSON_PROPERTY_COORDINATES,
  ConsignmentEvent.JSON_PROPERTY_WEIGHT_VOL_TEMP,
  ConsignmentEvent.JSON_PROPERTY_ATTRIBUTES,
  ConsignmentEvent.JSON_PROPERTY_AUDIT_LOG
})
@JsonTypeName("consignmentEvent")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class ConsignmentEvent {
  public static final String JSON_PROPERTY_CONSIGNMENT_NO = "consignmentNo";
  private String consignmentNo;

  public static final String JSON_PROPERTY_EVENT_DATE = "eventDate";
  private String eventDate;

  public static final String JSON_PROPERTY_EVENT_TIME = "eventTime";
  private String eventTime;

  public static final String JSON_PROPERTY_EVENT_CODE = "eventCode";
  private String eventCode;

  public static final String JSON_PROPERTY_ACTION_CODE = "actionCode";
  private String actionCode;

  public static final String JSON_PROPERTY_REASON_CODE = "reasonCode";
  private String reasonCode;

  public static final String JSON_PROPERTY_UNIT_CODE = "unitCode";
  private String unitCode;

  public static final String JSON_PROPERTY_POST_CODE = "postCode";
  private String postCode;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "countryCode";
  private String countryCode;

  public static final String JSON_PROPERTY_COMPANY_CODE = "companyCode";
  private String companyCode;

  public static final String JSON_PROPERTY_CONSIGNMENT_NO_SOURCE = "consignmentNoSource";
  private String consignmentNoSource;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_SYSTEM_CODE = "systemCode";
  private String systemCode;

  public static final String JSON_PROPERTY_SOURCE_SYSTEM = "sourceSystem";
  private String sourceSystem;

  public static final String JSON_PROPERTY_EQUIPMENT_TYPE = "equipmentType";
  private String equipmentType;

  public static final String JSON_PROPERTY_EQUIPMENT_ID = "equipmentId";
  private String equipmentId;

  public static final String JSON_PROPERTY_EQUIPMENT_MSG_COUNTER = "equipmentMsgCounter";
  private BigDecimal equipmentMsgCounter;

  public static final String JSON_PROPERTY_POST_REFERENCE = "postReference";
  private String postReference;

  public static final String JSON_PROPERTY_HANDED_OVER_TO_UNIT = "handedOverToUnit";
  private String handedOverToUnit;

  public static final String JSON_PROPERTY_SHELF_CODE = "shelfCode";
  private String shelfCode;

  public static final String JSON_PROPERTY_PICK_UP_CODE = "pickUpCode";
  private String pickUpCode;

  public static final String JSON_PROPERTY_RETURN_DATE = "returnDate";
  private String returnDate;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  private String comments;

  public static final String JSON_PROPERTY_DELIVERY_DETAILS = "deliveryDetails";
  private DeliveryDetails deliveryDetails;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  private Signature signature;

  public static final String JSON_PROPERTY_IMAGES = "images";
  private List<Images> images = null;

  public static final String JSON_PROPERTY_RBT_INFORMATION = "rbtInformation";
  private RbtInformation rbtInformation;

  public static final String JSON_PROPERTY_COORDINATES = "coordinates";
  private Coordinates coordinates;

  public static final String JSON_PROPERTY_WEIGHT_VOL_TEMP = "weightVolTemp";
  private WeightVolTemp weightVolTemp;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private Attributes attributes;

  public static final String JSON_PROPERTY_AUDIT_LOG = "auditLog";
  private AuditLog auditLog;


  public ConsignmentEvent consignmentNo(String consignmentNo) {
    
    this.consignmentNo = consignmentNo;
    return this;
  }

   /**
   * Get consignmentNo
   * @return consignmentNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONSIGNMENT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConsignmentNo() {
    return consignmentNo;
  }


  public void setConsignmentNo(String consignmentNo) {
    this.consignmentNo = consignmentNo;
  }


  public ConsignmentEvent eventDate(String eventDate) {
    
    this.eventDate = eventDate;
    return this;
  }

   /**
   * Get eventDate
   * @return eventDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EVENT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventDate() {
    return eventDate;
  }


  public void setEventDate(String eventDate) {
    this.eventDate = eventDate;
  }


  public ConsignmentEvent eventTime(String eventTime) {
    
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Get eventTime
   * @return eventTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EVENT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventTime() {
    return eventTime;
  }


  public void setEventTime(String eventTime) {
    this.eventTime = eventTime;
  }


  public ConsignmentEvent eventCode(String eventCode) {
    
    this.eventCode = eventCode;
    return this;
  }

   /**
   * Get eventCode
   * @return eventCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EVENT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventCode() {
    return eventCode;
  }


  public void setEventCode(String eventCode) {
    this.eventCode = eventCode;
  }


  public ConsignmentEvent actionCode(String actionCode) {
    
    this.actionCode = actionCode;
    return this;
  }

   /**
   * Get actionCode
   * @return actionCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getActionCode() {
    return actionCode;
  }


  public void setActionCode(String actionCode) {
    this.actionCode = actionCode;
  }


  public ConsignmentEvent reasonCode(String reasonCode) {
    
    this.reasonCode = reasonCode;
    return this;
  }

   /**
   * Get reasonCode
   * @return reasonCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReasonCode() {
    return reasonCode;
  }


  public void setReasonCode(String reasonCode) {
    this.reasonCode = reasonCode;
  }


  public ConsignmentEvent unitCode(String unitCode) {
    
    this.unitCode = unitCode;
    return this;
  }

   /**
   * Get unitCode
   * @return unitCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNIT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnitCode() {
    return unitCode;
  }


  public void setUnitCode(String unitCode) {
    this.unitCode = unitCode;
  }


  public ConsignmentEvent postCode(String postCode) {
    
    this.postCode = postCode;
    return this;
  }

   /**
   * Get postCode
   * @return postCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POST_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostCode() {
    return postCode;
  }


  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }


  public ConsignmentEvent countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountryCode() {
    return countryCode;
  }


  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public ConsignmentEvent companyCode(String companyCode) {
    
    this.companyCode = companyCode;
    return this;
  }

   /**
   * Get companyCode
   * @return companyCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COMPANY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCompanyCode() {
    return companyCode;
  }


  public void setCompanyCode(String companyCode) {
    this.companyCode = companyCode;
  }


  public ConsignmentEvent consignmentNoSource(String consignmentNoSource) {
    
    this.consignmentNoSource = consignmentNoSource;
    return this;
  }

   /**
   * Get consignmentNoSource
   * @return consignmentNoSource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONSIGNMENT_NO_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConsignmentNoSource() {
    return consignmentNoSource;
  }


  public void setConsignmentNoSource(String consignmentNoSource) {
    this.consignmentNoSource = consignmentNoSource;
  }


  public ConsignmentEvent status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public ConsignmentEvent systemCode(String systemCode) {
    
    this.systemCode = systemCode;
    return this;
  }

   /**
   * Get systemCode
   * @return systemCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SYSTEM_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSystemCode() {
    return systemCode;
  }


  public void setSystemCode(String systemCode) {
    this.systemCode = systemCode;
  }


  public ConsignmentEvent sourceSystem(String sourceSystem) {
    
    this.sourceSystem = sourceSystem;
    return this;
  }

   /**
   * Get sourceSystem
   * @return sourceSystem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceSystem() {
    return sourceSystem;
  }


  public void setSourceSystem(String sourceSystem) {
    this.sourceSystem = sourceSystem;
  }


  public ConsignmentEvent equipmentType(String equipmentType) {
    
    this.equipmentType = equipmentType;
    return this;
  }

   /**
   * Get equipmentType
   * @return equipmentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EQUIPMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEquipmentType() {
    return equipmentType;
  }


  public void setEquipmentType(String equipmentType) {
    this.equipmentType = equipmentType;
  }


  public ConsignmentEvent equipmentId(String equipmentId) {
    
    this.equipmentId = equipmentId;
    return this;
  }

   /**
   * Get equipmentId
   * @return equipmentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EQUIPMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEquipmentId() {
    return equipmentId;
  }


  public void setEquipmentId(String equipmentId) {
    this.equipmentId = equipmentId;
  }


  public ConsignmentEvent equipmentMsgCounter(BigDecimal equipmentMsgCounter) {
    
    this.equipmentMsgCounter = equipmentMsgCounter;
    return this;
  }

   /**
   * Get equipmentMsgCounter
   * @return equipmentMsgCounter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EQUIPMENT_MSG_COUNTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getEquipmentMsgCounter() {
    return equipmentMsgCounter;
  }


  public void setEquipmentMsgCounter(BigDecimal equipmentMsgCounter) {
    this.equipmentMsgCounter = equipmentMsgCounter;
  }


  public ConsignmentEvent postReference(String postReference) {
    
    this.postReference = postReference;
    return this;
  }

   /**
   * Get postReference
   * @return postReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POST_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostReference() {
    return postReference;
  }


  public void setPostReference(String postReference) {
    this.postReference = postReference;
  }


  public ConsignmentEvent handedOverToUnit(String handedOverToUnit) {
    
    this.handedOverToUnit = handedOverToUnit;
    return this;
  }

   /**
   * Get handedOverToUnit
   * @return handedOverToUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HANDED_OVER_TO_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHandedOverToUnit() {
    return handedOverToUnit;
  }


  public void setHandedOverToUnit(String handedOverToUnit) {
    this.handedOverToUnit = handedOverToUnit;
  }


  public ConsignmentEvent shelfCode(String shelfCode) {
    
    this.shelfCode = shelfCode;
    return this;
  }

   /**
   * Get shelfCode
   * @return shelfCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHELF_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShelfCode() {
    return shelfCode;
  }


  public void setShelfCode(String shelfCode) {
    this.shelfCode = shelfCode;
  }


  public ConsignmentEvent pickUpCode(String pickUpCode) {
    
    this.pickUpCode = pickUpCode;
    return this;
  }

   /**
   * Get pickUpCode
   * @return pickUpCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PICK_UP_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPickUpCode() {
    return pickUpCode;
  }


  public void setPickUpCode(String pickUpCode) {
    this.pickUpCode = pickUpCode;
  }


  public ConsignmentEvent returnDate(String returnDate) {
    
    this.returnDate = returnDate;
    return this;
  }

   /**
   * Get returnDate
   * @return returnDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RETURN_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReturnDate() {
    return returnDate;
  }


  public void setReturnDate(String returnDate) {
    this.returnDate = returnDate;
  }


  public ConsignmentEvent comments(String comments) {
    
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  public void setComments(String comments) {
    this.comments = comments;
  }


  public ConsignmentEvent deliveryDetails(DeliveryDetails deliveryDetails) {
    
    this.deliveryDetails = deliveryDetails;
    return this;
  }

   /**
   * Get deliveryDetails
   * @return deliveryDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELIVERY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeliveryDetails getDeliveryDetails() {
    return deliveryDetails;
  }


  public void setDeliveryDetails(DeliveryDetails deliveryDetails) {
    this.deliveryDetails = deliveryDetails;
  }


  public ConsignmentEvent signature(Signature signature) {
    
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Signature getSignature() {
    return signature;
  }


  public void setSignature(Signature signature) {
    this.signature = signature;
  }


  public ConsignmentEvent images(List<Images> images) {
    
    this.images = images;
    return this;
  }

  public ConsignmentEvent addImagesItem(Images imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Images> getImages() {
    return images;
  }


  public void setImages(List<Images> images) {
    this.images = images;
  }


  public ConsignmentEvent rbtInformation(RbtInformation rbtInformation) {
    
    this.rbtInformation = rbtInformation;
    return this;
  }

   /**
   * Get rbtInformation
   * @return rbtInformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RBT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RbtInformation getRbtInformation() {
    return rbtInformation;
  }


  public void setRbtInformation(RbtInformation rbtInformation) {
    this.rbtInformation = rbtInformation;
  }


  public ConsignmentEvent coordinates(Coordinates coordinates) {
    
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COORDINATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Coordinates getCoordinates() {
    return coordinates;
  }


  public void setCoordinates(Coordinates coordinates) {
    this.coordinates = coordinates;
  }


  public ConsignmentEvent weightVolTemp(WeightVolTemp weightVolTemp) {
    
    this.weightVolTemp = weightVolTemp;
    return this;
  }

   /**
   * Get weightVolTemp
   * @return weightVolTemp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WEIGHT_VOL_TEMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WeightVolTemp getWeightVolTemp() {
    return weightVolTemp;
  }


  public void setWeightVolTemp(WeightVolTemp weightVolTemp) {
    this.weightVolTemp = weightVolTemp;
  }


  public ConsignmentEvent attributes(Attributes attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Attributes getAttributes() {
    return attributes;
  }


  public void setAttributes(Attributes attributes) {
    this.attributes = attributes;
  }


  public ConsignmentEvent auditLog(AuditLog auditLog) {
    
    this.auditLog = auditLog;
    return this;
  }

   /**
   * Get auditLog
   * @return auditLog
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDIT_LOG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLog getAuditLog() {
    return auditLog;
  }


  public void setAuditLog(AuditLog auditLog) {
    this.auditLog = auditLog;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsignmentEvent consignmentEvent = (ConsignmentEvent) o;
    return Objects.equals(this.consignmentNo, consignmentEvent.consignmentNo) &&
        Objects.equals(this.eventDate, consignmentEvent.eventDate) &&
        Objects.equals(this.eventTime, consignmentEvent.eventTime) &&
        Objects.equals(this.eventCode, consignmentEvent.eventCode) &&
        Objects.equals(this.actionCode, consignmentEvent.actionCode) &&
        Objects.equals(this.reasonCode, consignmentEvent.reasonCode) &&
        Objects.equals(this.unitCode, consignmentEvent.unitCode) &&
        Objects.equals(this.postCode, consignmentEvent.postCode) &&
        Objects.equals(this.countryCode, consignmentEvent.countryCode) &&
        Objects.equals(this.companyCode, consignmentEvent.companyCode) &&
        Objects.equals(this.consignmentNoSource, consignmentEvent.consignmentNoSource) &&
        Objects.equals(this.status, consignmentEvent.status) &&
        Objects.equals(this.systemCode, consignmentEvent.systemCode) &&
        Objects.equals(this.sourceSystem, consignmentEvent.sourceSystem) &&
        Objects.equals(this.equipmentType, consignmentEvent.equipmentType) &&
        Objects.equals(this.equipmentId, consignmentEvent.equipmentId) &&
        Objects.equals(this.equipmentMsgCounter, consignmentEvent.equipmentMsgCounter) &&
        Objects.equals(this.postReference, consignmentEvent.postReference) &&
        Objects.equals(this.handedOverToUnit, consignmentEvent.handedOverToUnit) &&
        Objects.equals(this.shelfCode, consignmentEvent.shelfCode) &&
        Objects.equals(this.pickUpCode, consignmentEvent.pickUpCode) &&
        Objects.equals(this.returnDate, consignmentEvent.returnDate) &&
        Objects.equals(this.comments, consignmentEvent.comments) &&
        Objects.equals(this.deliveryDetails, consignmentEvent.deliveryDetails) &&
        Objects.equals(this.signature, consignmentEvent.signature) &&
        Objects.equals(this.images, consignmentEvent.images) &&
        Objects.equals(this.rbtInformation, consignmentEvent.rbtInformation) &&
        Objects.equals(this.coordinates, consignmentEvent.coordinates) &&
        Objects.equals(this.weightVolTemp, consignmentEvent.weightVolTemp) &&
        Objects.equals(this.attributes, consignmentEvent.attributes) &&
        Objects.equals(this.auditLog, consignmentEvent.auditLog);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consignmentNo, eventDate, eventTime, eventCode, actionCode, reasonCode, unitCode, postCode, countryCode, companyCode, consignmentNoSource, status, systemCode, sourceSystem, equipmentType, equipmentId, equipmentMsgCounter, postReference, handedOverToUnit, shelfCode, pickUpCode, returnDate, comments, deliveryDetails, signature, images, rbtInformation, coordinates, weightVolTemp, attributes, auditLog);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsignmentEvent {\n");
    sb.append("    consignmentNo: ").append(toIndentedString(consignmentNo)).append("\n");
    sb.append("    eventDate: ").append(toIndentedString(eventDate)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    eventCode: ").append(toIndentedString(eventCode)).append("\n");
    sb.append("    actionCode: ").append(toIndentedString(actionCode)).append("\n");
    sb.append("    reasonCode: ").append(toIndentedString(reasonCode)).append("\n");
    sb.append("    unitCode: ").append(toIndentedString(unitCode)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    companyCode: ").append(toIndentedString(companyCode)).append("\n");
    sb.append("    consignmentNoSource: ").append(toIndentedString(consignmentNoSource)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    systemCode: ").append(toIndentedString(systemCode)).append("\n");
    sb.append("    sourceSystem: ").append(toIndentedString(sourceSystem)).append("\n");
    sb.append("    equipmentType: ").append(toIndentedString(equipmentType)).append("\n");
    sb.append("    equipmentId: ").append(toIndentedString(equipmentId)).append("\n");
    sb.append("    equipmentMsgCounter: ").append(toIndentedString(equipmentMsgCounter)).append("\n");
    sb.append("    postReference: ").append(toIndentedString(postReference)).append("\n");
    sb.append("    handedOverToUnit: ").append(toIndentedString(handedOverToUnit)).append("\n");
    sb.append("    shelfCode: ").append(toIndentedString(shelfCode)).append("\n");
    sb.append("    pickUpCode: ").append(toIndentedString(pickUpCode)).append("\n");
    sb.append("    returnDate: ").append(toIndentedString(returnDate)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    deliveryDetails: ").append(toIndentedString(deliveryDetails)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    rbtInformation: ").append(toIndentedString(rbtInformation)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    weightVolTemp: ").append(toIndentedString(weightVolTemp)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    auditLog: ").append(toIndentedString(auditLog)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

