/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import no.posten.ph.consignment.model.AuditLog;
import no.posten.ph.consignment.model.CashOnDelivery;
import no.posten.ph.consignment.model.Charges;
import no.posten.ph.consignment.model.ConsignmentEvent;
import no.posten.ph.consignment.model.DangerousGoods;
import no.posten.ph.consignment.model.DateAndTime;
import no.posten.ph.consignment.model.Equipment;
import no.posten.ph.consignment.model.FreeText;
import no.posten.ph.consignment.model.Insurance;
import no.posten.ph.consignment.model.Party;
import no.posten.ph.consignment.model.PartyConsignee;
import no.posten.ph.consignment.model.PartyConsignor;
import no.posten.ph.consignment.model.Reference;
import no.posten.ph.consignment.model.TrackingRecipients;
import no.posten.ph.consignment.model.Vas;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Consignment
 */
@JsonPropertyOrder({
  Consignment.JSON_PROPERTY_CONSIGNMENT_NO,
  Consignment.JSON_PROPERTY_CONSIGNMENT_NO_TYPE,
  Consignment.JSON_PROPERTY_CONSIGNMENT_NO_IDENTIFIER,
  Consignment.JSON_PROPERTY_CONSIGNMENT_NO_ISSUER,
  Consignment.JSON_PROPERTY_CONSIGNMENT_MASTER,
  Consignment.JSON_PROPERTY_PRODUCT_CODE,
  Consignment.JSON_PROPERTY_SERVICE_GROUP,
  Consignment.JSON_PROPERTY_TERMS_OF_DELIVER,
  Consignment.JSON_PROPERTY_NUMBER_OF_PACKAGES,
  Consignment.JSON_PROPERTY_NET_WEIGHT,
  Consignment.JSON_PROPERTY_GROSS_WEIGHT,
  Consignment.JSON_PROPERTY_GROSS_VOLUME,
  Consignment.JSON_PROPERTY_LOADING_METRES,
  Consignment.JSON_PROPERTY_PALLET_FOOTPRINTS,
  Consignment.JSON_PROPERTY_GOODS_DESCRIPTION,
  Consignment.JSON_PROPERTY_DGS_TOTAL_POINTS,
  Consignment.JSON_PROPERTY_TERMS_TYPE,
  Consignment.JSON_PROPERTY_TERMS_CODE,
  Consignment.JSON_PROPERTY_TERMS_LOCATION,
  Consignment.JSON_PROPERTY_TEMPERATURE_TRANSPORT_MIN,
  Consignment.JSON_PROPERTY_TEMPERATURE_TRANSPORT_MAX,
  Consignment.JSON_PROPERTY_TEMPERATURE_STORAGE_MIN,
  Consignment.JSON_PROPERTY_TEMPERATURE_STORAGE_MAX,
  Consignment.JSON_PROPERTY_AGREED_DISCOUNT,
  Consignment.JSON_PROPERTY_ORDER_TYPE,
  Consignment.JSON_PROPERTY_DISCOUNT_REGISTERED_BY,
  Consignment.JSON_PROPERTY_BOOKING_REFERENCE,
  Consignment.JSON_PROPERTY_SYNTHETIC_STATUS,
  Consignment.JSON_PROPERTY_RECEIVER_REFERENCE,
  Consignment.JSON_PROPERTY_VAS,
  Consignment.JSON_PROPERTY_REFERENCE,
  Consignment.JSON_PROPERTY_FREE_TEXT,
  Consignment.JSON_PROPERTY_DATE_TIME,
  Consignment.JSON_PROPERTY_TRACKING_RECIPIENTS,
  Consignment.JSON_PROPERTY_PARTY_CONSIGNOR,
  Consignment.JSON_PROPERTY_PARTY_CONSIGNEE,
  Consignment.JSON_PROPERTY_PARTY,
  Consignment.JSON_PROPERTY_DANGEROUS_GOODS,
  Consignment.JSON_PROPERTY_CASH_ON_DELIVERY,
  Consignment.JSON_PROPERTY_CHARGES,
  Consignment.JSON_PROPERTY_INSURANCE,
  Consignment.JSON_PROPERTY_EQUIPMENT,
  Consignment.JSON_PROPERTY_AUDIT_LOG,
  Consignment.JSON_PROPERTY_CONSIGNMENT_EVENT
})
@JsonTypeName("consignment")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class Consignment {
  public static final String JSON_PROPERTY_CONSIGNMENT_NO = "consignmentNo";
  private String consignmentNo;

  public static final String JSON_PROPERTY_CONSIGNMENT_NO_TYPE = "consignmentNoType";
  private String consignmentNoType;

  public static final String JSON_PROPERTY_CONSIGNMENT_NO_IDENTIFIER = "consignmentNoIdentifier";
  private String consignmentNoIdentifier;

  public static final String JSON_PROPERTY_CONSIGNMENT_NO_ISSUER = "consignmentNoIssuer";
  private String consignmentNoIssuer;

  public static final String JSON_PROPERTY_CONSIGNMENT_MASTER = "consignmentMaster";
  private String consignmentMaster;

  public static final String JSON_PROPERTY_PRODUCT_CODE = "productCode";
  private String productCode;

  public static final String JSON_PROPERTY_SERVICE_GROUP = "serviceGroup";
  private String serviceGroup;

  public static final String JSON_PROPERTY_TERMS_OF_DELIVER = "termsOfDeliver";
  private String termsOfDeliver;

  public static final String JSON_PROPERTY_NUMBER_OF_PACKAGES = "numberOfPackages";
  private Integer numberOfPackages;

  public static final String JSON_PROPERTY_NET_WEIGHT = "netWeight";
  private Long netWeight;

  public static final String JSON_PROPERTY_GROSS_WEIGHT = "grossWeight";
  private Long grossWeight;

  public static final String JSON_PROPERTY_GROSS_VOLUME = "grossVolume";
  private Integer grossVolume;

  public static final String JSON_PROPERTY_LOADING_METRES = "loadingMetres";
  private BigDecimal loadingMetres;

  public static final String JSON_PROPERTY_PALLET_FOOTPRINTS = "palletFootprints";
  private Long palletFootprints;

  public static final String JSON_PROPERTY_GOODS_DESCRIPTION = "goodsDescription";
  private String goodsDescription;

  public static final String JSON_PROPERTY_DGS_TOTAL_POINTS = "dgsTotalPoints";
  private Integer dgsTotalPoints;

  public static final String JSON_PROPERTY_TERMS_TYPE = "termsType";
  private String termsType;

  public static final String JSON_PROPERTY_TERMS_CODE = "termsCode";
  private String termsCode;

  public static final String JSON_PROPERTY_TERMS_LOCATION = "termsLocation";
  private String termsLocation;

  public static final String JSON_PROPERTY_TEMPERATURE_TRANSPORT_MIN = "temperatureTransportMin";
  private BigDecimal temperatureTransportMin;

  public static final String JSON_PROPERTY_TEMPERATURE_TRANSPORT_MAX = "temperatureTransportMax";
  private BigDecimal temperatureTransportMax;

  public static final String JSON_PROPERTY_TEMPERATURE_STORAGE_MIN = "temperatureStorageMin";
  private BigDecimal temperatureStorageMin;

  public static final String JSON_PROPERTY_TEMPERATURE_STORAGE_MAX = "temperatureStorageMax";
  private BigDecimal temperatureStorageMax;

  public static final String JSON_PROPERTY_AGREED_DISCOUNT = "agreedDiscount";
  private BigDecimal agreedDiscount;

  public static final String JSON_PROPERTY_ORDER_TYPE = "orderType";
  private String orderType;

  public static final String JSON_PROPERTY_DISCOUNT_REGISTERED_BY = "discountRegisteredBy";
  private String discountRegisteredBy;

  public static final String JSON_PROPERTY_BOOKING_REFERENCE = "bookingReference";
  private String bookingReference;

  public static final String JSON_PROPERTY_SYNTHETIC_STATUS = "syntheticStatus";
  private String syntheticStatus;

  public static final String JSON_PROPERTY_RECEIVER_REFERENCE = "receiverReference";
  private String receiverReference;

  public static final String JSON_PROPERTY_VAS = "vas";
  private List<Vas> vas = null;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  private List<Reference> reference = null;

  public static final String JSON_PROPERTY_FREE_TEXT = "freeText";
  private List<FreeText> freeText = null;

  public static final String JSON_PROPERTY_DATE_TIME = "dateTime";
  private List<DateAndTime> dateTime = null;

  public static final String JSON_PROPERTY_TRACKING_RECIPIENTS = "trackingRecipients";
  private List<TrackingRecipients> trackingRecipients = null;

  public static final String JSON_PROPERTY_PARTY_CONSIGNOR = "partyConsignor";
  private PartyConsignor partyConsignor;

  public static final String JSON_PROPERTY_PARTY_CONSIGNEE = "partyConsignee";
  private PartyConsignee partyConsignee;

  public static final String JSON_PROPERTY_PARTY = "party";
  private List<Party> party = null;

  public static final String JSON_PROPERTY_DANGEROUS_GOODS = "dangerousGoods";
  private List<DangerousGoods> dangerousGoods = null;

  public static final String JSON_PROPERTY_CASH_ON_DELIVERY = "cashOnDelivery";
  private CashOnDelivery cashOnDelivery;

  public static final String JSON_PROPERTY_CHARGES = "charges";
  private List<Charges> charges = null;

  public static final String JSON_PROPERTY_INSURANCE = "insurance";
  private Insurance insurance;

  public static final String JSON_PROPERTY_EQUIPMENT = "equipment";
  private List<Equipment> equipment = null;

  public static final String JSON_PROPERTY_AUDIT_LOG = "auditLog";
  private AuditLog auditLog;

  public static final String JSON_PROPERTY_CONSIGNMENT_EVENT = "consignmentEvent";
  private List<ConsignmentEvent> consignmentEvent = null;


  public Consignment consignmentNo(String consignmentNo) {
    
    this.consignmentNo = consignmentNo;
    return this;
  }

   /**
   * Get consignmentNo
   * @return consignmentNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONSIGNMENT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConsignmentNo() {
    return consignmentNo;
  }


  public void setConsignmentNo(String consignmentNo) {
    this.consignmentNo = consignmentNo;
  }


  public Consignment consignmentNoType(String consignmentNoType) {
    
    this.consignmentNoType = consignmentNoType;
    return this;
  }

   /**
   * Get consignmentNoType
   * @return consignmentNoType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONSIGNMENT_NO_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConsignmentNoType() {
    return consignmentNoType;
  }


  public void setConsignmentNoType(String consignmentNoType) {
    this.consignmentNoType = consignmentNoType;
  }


  public Consignment consignmentNoIdentifier(String consignmentNoIdentifier) {
    
    this.consignmentNoIdentifier = consignmentNoIdentifier;
    return this;
  }

   /**
   * Get consignmentNoIdentifier
   * @return consignmentNoIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONSIGNMENT_NO_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConsignmentNoIdentifier() {
    return consignmentNoIdentifier;
  }


  public void setConsignmentNoIdentifier(String consignmentNoIdentifier) {
    this.consignmentNoIdentifier = consignmentNoIdentifier;
  }


  public Consignment consignmentNoIssuer(String consignmentNoIssuer) {
    
    this.consignmentNoIssuer = consignmentNoIssuer;
    return this;
  }

   /**
   * Get consignmentNoIssuer
   * @return consignmentNoIssuer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONSIGNMENT_NO_ISSUER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConsignmentNoIssuer() {
    return consignmentNoIssuer;
  }


  public void setConsignmentNoIssuer(String consignmentNoIssuer) {
    this.consignmentNoIssuer = consignmentNoIssuer;
  }


  public Consignment consignmentMaster(String consignmentMaster) {
    
    this.consignmentMaster = consignmentMaster;
    return this;
  }

   /**
   * Get consignmentMaster
   * @return consignmentMaster
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONSIGNMENT_MASTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConsignmentMaster() {
    return consignmentMaster;
  }


  public void setConsignmentMaster(String consignmentMaster) {
    this.consignmentMaster = consignmentMaster;
  }


  public Consignment productCode(String productCode) {
    
    this.productCode = productCode;
    return this;
  }

   /**
   * Get productCode
   * @return productCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductCode() {
    return productCode;
  }


  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }


  public Consignment serviceGroup(String serviceGroup) {
    
    this.serviceGroup = serviceGroup;
    return this;
  }

   /**
   * Get serviceGroup
   * @return serviceGroup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERVICE_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceGroup() {
    return serviceGroup;
  }


  public void setServiceGroup(String serviceGroup) {
    this.serviceGroup = serviceGroup;
  }


  public Consignment termsOfDeliver(String termsOfDeliver) {
    
    this.termsOfDeliver = termsOfDeliver;
    return this;
  }

   /**
   * Get termsOfDeliver
   * @return termsOfDeliver
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TERMS_OF_DELIVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTermsOfDeliver() {
    return termsOfDeliver;
  }


  public void setTermsOfDeliver(String termsOfDeliver) {
    this.termsOfDeliver = termsOfDeliver;
  }


  public Consignment numberOfPackages(Integer numberOfPackages) {
    
    this.numberOfPackages = numberOfPackages;
    return this;
  }

   /**
   * Get numberOfPackages
   * @return numberOfPackages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NUMBER_OF_PACKAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumberOfPackages() {
    return numberOfPackages;
  }


  public void setNumberOfPackages(Integer numberOfPackages) {
    this.numberOfPackages = numberOfPackages;
  }


  public Consignment netWeight(Long netWeight) {
    
    this.netWeight = netWeight;
    return this;
  }

   /**
   * Get netWeight
   * @return netWeight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NET_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNetWeight() {
    return netWeight;
  }


  public void setNetWeight(Long netWeight) {
    this.netWeight = netWeight;
  }


  public Consignment grossWeight(Long grossWeight) {
    
    this.grossWeight = grossWeight;
    return this;
  }

   /**
   * Get grossWeight
   * @return grossWeight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GROSS_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getGrossWeight() {
    return grossWeight;
  }


  public void setGrossWeight(Long grossWeight) {
    this.grossWeight = grossWeight;
  }


  public Consignment grossVolume(Integer grossVolume) {
    
    this.grossVolume = grossVolume;
    return this;
  }

   /**
   * Get grossVolume
   * @return grossVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GROSS_VOLUME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getGrossVolume() {
    return grossVolume;
  }


  public void setGrossVolume(Integer grossVolume) {
    this.grossVolume = grossVolume;
  }


  public Consignment loadingMetres(BigDecimal loadingMetres) {
    
    this.loadingMetres = loadingMetres;
    return this;
  }

   /**
   * Get loadingMetres
   * @return loadingMetres
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOADING_METRES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLoadingMetres() {
    return loadingMetres;
  }


  public void setLoadingMetres(BigDecimal loadingMetres) {
    this.loadingMetres = loadingMetres;
  }


  public Consignment palletFootprints(Long palletFootprints) {
    
    this.palletFootprints = palletFootprints;
    return this;
  }

   /**
   * Get palletFootprints
   * @return palletFootprints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PALLET_FOOTPRINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPalletFootprints() {
    return palletFootprints;
  }


  public void setPalletFootprints(Long palletFootprints) {
    this.palletFootprints = palletFootprints;
  }


  public Consignment goodsDescription(String goodsDescription) {
    
    this.goodsDescription = goodsDescription;
    return this;
  }

   /**
   * Get goodsDescription
   * @return goodsDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GOODS_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGoodsDescription() {
    return goodsDescription;
  }


  public void setGoodsDescription(String goodsDescription) {
    this.goodsDescription = goodsDescription;
  }


  public Consignment dgsTotalPoints(Integer dgsTotalPoints) {
    
    this.dgsTotalPoints = dgsTotalPoints;
    return this;
  }

   /**
   * Get dgsTotalPoints
   * @return dgsTotalPoints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DGS_TOTAL_POINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDgsTotalPoints() {
    return dgsTotalPoints;
  }


  public void setDgsTotalPoints(Integer dgsTotalPoints) {
    this.dgsTotalPoints = dgsTotalPoints;
  }


  public Consignment termsType(String termsType) {
    
    this.termsType = termsType;
    return this;
  }

   /**
   * Get termsType
   * @return termsType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TERMS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTermsType() {
    return termsType;
  }


  public void setTermsType(String termsType) {
    this.termsType = termsType;
  }


  public Consignment termsCode(String termsCode) {
    
    this.termsCode = termsCode;
    return this;
  }

   /**
   * Get termsCode
   * @return termsCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TERMS_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTermsCode() {
    return termsCode;
  }


  public void setTermsCode(String termsCode) {
    this.termsCode = termsCode;
  }


  public Consignment termsLocation(String termsLocation) {
    
    this.termsLocation = termsLocation;
    return this;
  }

   /**
   * Get termsLocation
   * @return termsLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TERMS_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTermsLocation() {
    return termsLocation;
  }


  public void setTermsLocation(String termsLocation) {
    this.termsLocation = termsLocation;
  }


  public Consignment temperatureTransportMin(BigDecimal temperatureTransportMin) {
    
    this.temperatureTransportMin = temperatureTransportMin;
    return this;
  }

   /**
   * Get temperatureTransportMin
   * @return temperatureTransportMin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEMPERATURE_TRANSPORT_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTemperatureTransportMin() {
    return temperatureTransportMin;
  }


  public void setTemperatureTransportMin(BigDecimal temperatureTransportMin) {
    this.temperatureTransportMin = temperatureTransportMin;
  }


  public Consignment temperatureTransportMax(BigDecimal temperatureTransportMax) {
    
    this.temperatureTransportMax = temperatureTransportMax;
    return this;
  }

   /**
   * Get temperatureTransportMax
   * @return temperatureTransportMax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEMPERATURE_TRANSPORT_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTemperatureTransportMax() {
    return temperatureTransportMax;
  }


  public void setTemperatureTransportMax(BigDecimal temperatureTransportMax) {
    this.temperatureTransportMax = temperatureTransportMax;
  }


  public Consignment temperatureStorageMin(BigDecimal temperatureStorageMin) {
    
    this.temperatureStorageMin = temperatureStorageMin;
    return this;
  }

   /**
   * Get temperatureStorageMin
   * @return temperatureStorageMin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEMPERATURE_STORAGE_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTemperatureStorageMin() {
    return temperatureStorageMin;
  }


  public void setTemperatureStorageMin(BigDecimal temperatureStorageMin) {
    this.temperatureStorageMin = temperatureStorageMin;
  }


  public Consignment temperatureStorageMax(BigDecimal temperatureStorageMax) {
    
    this.temperatureStorageMax = temperatureStorageMax;
    return this;
  }

   /**
   * Get temperatureStorageMax
   * @return temperatureStorageMax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEMPERATURE_STORAGE_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTemperatureStorageMax() {
    return temperatureStorageMax;
  }


  public void setTemperatureStorageMax(BigDecimal temperatureStorageMax) {
    this.temperatureStorageMax = temperatureStorageMax;
  }


  public Consignment agreedDiscount(BigDecimal agreedDiscount) {
    
    this.agreedDiscount = agreedDiscount;
    return this;
  }

   /**
   * Get agreedDiscount
   * @return agreedDiscount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AGREED_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getAgreedDiscount() {
    return agreedDiscount;
  }


  public void setAgreedDiscount(BigDecimal agreedDiscount) {
    this.agreedDiscount = agreedDiscount;
  }


  public Consignment orderType(String orderType) {
    
    this.orderType = orderType;
    return this;
  }

   /**
   * Get orderType
   * @return orderType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderType() {
    return orderType;
  }


  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }


  public Consignment discountRegisteredBy(String discountRegisteredBy) {
    
    this.discountRegisteredBy = discountRegisteredBy;
    return this;
  }

   /**
   * Get discountRegisteredBy
   * @return discountRegisteredBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISCOUNT_REGISTERED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDiscountRegisteredBy() {
    return discountRegisteredBy;
  }


  public void setDiscountRegisteredBy(String discountRegisteredBy) {
    this.discountRegisteredBy = discountRegisteredBy;
  }


  public Consignment bookingReference(String bookingReference) {
    
    this.bookingReference = bookingReference;
    return this;
  }

   /**
   * Get bookingReference
   * @return bookingReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BOOKING_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBookingReference() {
    return bookingReference;
  }


  public void setBookingReference(String bookingReference) {
    this.bookingReference = bookingReference;
  }


  public Consignment syntheticStatus(String syntheticStatus) {
    
    this.syntheticStatus = syntheticStatus;
    return this;
  }

   /**
   * Get syntheticStatus
   * @return syntheticStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SYNTHETIC_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSyntheticStatus() {
    return syntheticStatus;
  }


  public void setSyntheticStatus(String syntheticStatus) {
    this.syntheticStatus = syntheticStatus;
  }


  public Consignment receiverReference(String receiverReference) {
    
    this.receiverReference = receiverReference;
    return this;
  }

   /**
   * Get receiverReference
   * @return receiverReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIVER_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReceiverReference() {
    return receiverReference;
  }


  public void setReceiverReference(String receiverReference) {
    this.receiverReference = receiverReference;
  }


  public Consignment vas(List<Vas> vas) {
    
    this.vas = vas;
    return this;
  }

  public Consignment addVasItem(Vas vasItem) {
    if (this.vas == null) {
      this.vas = new ArrayList<>();
    }
    this.vas.add(vasItem);
    return this;
  }

   /**
   * Get vas
   * @return vas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Vas> getVas() {
    return vas;
  }


  public void setVas(List<Vas> vas) {
    this.vas = vas;
  }


  public Consignment reference(List<Reference> reference) {
    
    this.reference = reference;
    return this;
  }

  public Consignment addReferenceItem(Reference referenceItem) {
    if (this.reference == null) {
      this.reference = new ArrayList<>();
    }
    this.reference.add(referenceItem);
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Reference> getReference() {
    return reference;
  }


  public void setReference(List<Reference> reference) {
    this.reference = reference;
  }


  public Consignment freeText(List<FreeText> freeText) {
    
    this.freeText = freeText;
    return this;
  }

  public Consignment addFreeTextItem(FreeText freeTextItem) {
    if (this.freeText == null) {
      this.freeText = new ArrayList<>();
    }
    this.freeText.add(freeTextItem);
    return this;
  }

   /**
   * Get freeText
   * @return freeText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FREE_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FreeText> getFreeText() {
    return freeText;
  }


  public void setFreeText(List<FreeText> freeText) {
    this.freeText = freeText;
  }


  public Consignment dateTime(List<DateAndTime> dateTime) {
    
    this.dateTime = dateTime;
    return this;
  }

  public Consignment addDateTimeItem(DateAndTime dateTimeItem) {
    if (this.dateTime == null) {
      this.dateTime = new ArrayList<>();
    }
    this.dateTime.add(dateTimeItem);
    return this;
  }

   /**
   * Get dateTime
   * @return dateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DateAndTime> getDateTime() {
    return dateTime;
  }


  public void setDateTime(List<DateAndTime> dateTime) {
    this.dateTime = dateTime;
  }


  public Consignment trackingRecipients(List<TrackingRecipients> trackingRecipients) {
    
    this.trackingRecipients = trackingRecipients;
    return this;
  }

  public Consignment addTrackingRecipientsItem(TrackingRecipients trackingRecipientsItem) {
    if (this.trackingRecipients == null) {
      this.trackingRecipients = new ArrayList<>();
    }
    this.trackingRecipients.add(trackingRecipientsItem);
    return this;
  }

   /**
   * Get trackingRecipients
   * @return trackingRecipients
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRACKING_RECIPIENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TrackingRecipients> getTrackingRecipients() {
    return trackingRecipients;
  }


  public void setTrackingRecipients(List<TrackingRecipients> trackingRecipients) {
    this.trackingRecipients = trackingRecipients;
  }


  public Consignment partyConsignor(PartyConsignor partyConsignor) {
    
    this.partyConsignor = partyConsignor;
    return this;
  }

   /**
   * Get partyConsignor
   * @return partyConsignor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARTY_CONSIGNOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PartyConsignor getPartyConsignor() {
    return partyConsignor;
  }


  public void setPartyConsignor(PartyConsignor partyConsignor) {
    this.partyConsignor = partyConsignor;
  }


  public Consignment partyConsignee(PartyConsignee partyConsignee) {
    
    this.partyConsignee = partyConsignee;
    return this;
  }

   /**
   * Get partyConsignee
   * @return partyConsignee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARTY_CONSIGNEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PartyConsignee getPartyConsignee() {
    return partyConsignee;
  }


  public void setPartyConsignee(PartyConsignee partyConsignee) {
    this.partyConsignee = partyConsignee;
  }


  public Consignment party(List<Party> party) {
    
    this.party = party;
    return this;
  }

  public Consignment addPartyItem(Party partyItem) {
    if (this.party == null) {
      this.party = new ArrayList<>();
    }
    this.party.add(partyItem);
    return this;
  }

   /**
   * Get party
   * @return party
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Party> getParty() {
    return party;
  }


  public void setParty(List<Party> party) {
    this.party = party;
  }


  public Consignment dangerousGoods(List<DangerousGoods> dangerousGoods) {
    
    this.dangerousGoods = dangerousGoods;
    return this;
  }

  public Consignment addDangerousGoodsItem(DangerousGoods dangerousGoodsItem) {
    if (this.dangerousGoods == null) {
      this.dangerousGoods = new ArrayList<>();
    }
    this.dangerousGoods.add(dangerousGoodsItem);
    return this;
  }

   /**
   * Get dangerousGoods
   * @return dangerousGoods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DANGEROUS_GOODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DangerousGoods> getDangerousGoods() {
    return dangerousGoods;
  }


  public void setDangerousGoods(List<DangerousGoods> dangerousGoods) {
    this.dangerousGoods = dangerousGoods;
  }


  public Consignment cashOnDelivery(CashOnDelivery cashOnDelivery) {
    
    this.cashOnDelivery = cashOnDelivery;
    return this;
  }

   /**
   * Get cashOnDelivery
   * @return cashOnDelivery
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CASH_ON_DELIVERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CashOnDelivery getCashOnDelivery() {
    return cashOnDelivery;
  }


  public void setCashOnDelivery(CashOnDelivery cashOnDelivery) {
    this.cashOnDelivery = cashOnDelivery;
  }


  public Consignment charges(List<Charges> charges) {
    
    this.charges = charges;
    return this;
  }

  public Consignment addChargesItem(Charges chargesItem) {
    if (this.charges == null) {
      this.charges = new ArrayList<>();
    }
    this.charges.add(chargesItem);
    return this;
  }

   /**
   * Get charges
   * @return charges
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHARGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Charges> getCharges() {
    return charges;
  }


  public void setCharges(List<Charges> charges) {
    this.charges = charges;
  }


  public Consignment insurance(Insurance insurance) {
    
    this.insurance = insurance;
    return this;
  }

   /**
   * Get insurance
   * @return insurance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INSURANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Insurance getInsurance() {
    return insurance;
  }


  public void setInsurance(Insurance insurance) {
    this.insurance = insurance;
  }


  public Consignment equipment(List<Equipment> equipment) {
    
    this.equipment = equipment;
    return this;
  }

  public Consignment addEquipmentItem(Equipment equipmentItem) {
    if (this.equipment == null) {
      this.equipment = new ArrayList<>();
    }
    this.equipment.add(equipmentItem);
    return this;
  }

   /**
   * Get equipment
   * @return equipment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Equipment> getEquipment() {
    return equipment;
  }


  public void setEquipment(List<Equipment> equipment) {
    this.equipment = equipment;
  }


  public Consignment auditLog(AuditLog auditLog) {
    
    this.auditLog = auditLog;
    return this;
  }

   /**
   * Get auditLog
   * @return auditLog
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDIT_LOG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditLog getAuditLog() {
    return auditLog;
  }


  public void setAuditLog(AuditLog auditLog) {
    this.auditLog = auditLog;
  }


  public Consignment consignmentEvent(List<ConsignmentEvent> consignmentEvent) {
    
    this.consignmentEvent = consignmentEvent;
    return this;
  }

  public Consignment addConsignmentEventItem(ConsignmentEvent consignmentEventItem) {
    if (this.consignmentEvent == null) {
      this.consignmentEvent = new ArrayList<>();
    }
    this.consignmentEvent.add(consignmentEventItem);
    return this;
  }

   /**
   * Get consignmentEvent
   * @return consignmentEvent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONSIGNMENT_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ConsignmentEvent> getConsignmentEvent() {
    return consignmentEvent;
  }


  public void setConsignmentEvent(List<ConsignmentEvent> consignmentEvent) {
    this.consignmentEvent = consignmentEvent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Consignment consignment = (Consignment) o;
    return Objects.equals(this.consignmentNo, consignment.consignmentNo) &&
        Objects.equals(this.consignmentNoType, consignment.consignmentNoType) &&
        Objects.equals(this.consignmentNoIdentifier, consignment.consignmentNoIdentifier) &&
        Objects.equals(this.consignmentNoIssuer, consignment.consignmentNoIssuer) &&
        Objects.equals(this.consignmentMaster, consignment.consignmentMaster) &&
        Objects.equals(this.productCode, consignment.productCode) &&
        Objects.equals(this.serviceGroup, consignment.serviceGroup) &&
        Objects.equals(this.termsOfDeliver, consignment.termsOfDeliver) &&
        Objects.equals(this.numberOfPackages, consignment.numberOfPackages) &&
        Objects.equals(this.netWeight, consignment.netWeight) &&
        Objects.equals(this.grossWeight, consignment.grossWeight) &&
        Objects.equals(this.grossVolume, consignment.grossVolume) &&
        Objects.equals(this.loadingMetres, consignment.loadingMetres) &&
        Objects.equals(this.palletFootprints, consignment.palletFootprints) &&
        Objects.equals(this.goodsDescription, consignment.goodsDescription) &&
        Objects.equals(this.dgsTotalPoints, consignment.dgsTotalPoints) &&
        Objects.equals(this.termsType, consignment.termsType) &&
        Objects.equals(this.termsCode, consignment.termsCode) &&
        Objects.equals(this.termsLocation, consignment.termsLocation) &&
        Objects.equals(this.temperatureTransportMin, consignment.temperatureTransportMin) &&
        Objects.equals(this.temperatureTransportMax, consignment.temperatureTransportMax) &&
        Objects.equals(this.temperatureStorageMin, consignment.temperatureStorageMin) &&
        Objects.equals(this.temperatureStorageMax, consignment.temperatureStorageMax) &&
        Objects.equals(this.agreedDiscount, consignment.agreedDiscount) &&
        Objects.equals(this.orderType, consignment.orderType) &&
        Objects.equals(this.discountRegisteredBy, consignment.discountRegisteredBy) &&
        Objects.equals(this.bookingReference, consignment.bookingReference) &&
        Objects.equals(this.syntheticStatus, consignment.syntheticStatus) &&
        Objects.equals(this.receiverReference, consignment.receiverReference) &&
        Objects.equals(this.vas, consignment.vas) &&
        Objects.equals(this.reference, consignment.reference) &&
        Objects.equals(this.freeText, consignment.freeText) &&
        Objects.equals(this.dateTime, consignment.dateTime) &&
        Objects.equals(this.trackingRecipients, consignment.trackingRecipients) &&
        Objects.equals(this.partyConsignor, consignment.partyConsignor) &&
        Objects.equals(this.partyConsignee, consignment.partyConsignee) &&
        Objects.equals(this.party, consignment.party) &&
        Objects.equals(this.dangerousGoods, consignment.dangerousGoods) &&
        Objects.equals(this.cashOnDelivery, consignment.cashOnDelivery) &&
        Objects.equals(this.charges, consignment.charges) &&
        Objects.equals(this.insurance, consignment.insurance) &&
        Objects.equals(this.equipment, consignment.equipment) &&
        Objects.equals(this.auditLog, consignment.auditLog) &&
        Objects.equals(this.consignmentEvent, consignment.consignmentEvent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consignmentNo, consignmentNoType, consignmentNoIdentifier, consignmentNoIssuer, consignmentMaster, productCode, serviceGroup, termsOfDeliver, numberOfPackages, netWeight, grossWeight, grossVolume, loadingMetres, palletFootprints, goodsDescription, dgsTotalPoints, termsType, termsCode, termsLocation, temperatureTransportMin, temperatureTransportMax, temperatureStorageMin, temperatureStorageMax, agreedDiscount, orderType, discountRegisteredBy, bookingReference, syntheticStatus, receiverReference, vas, reference, freeText, dateTime, trackingRecipients, partyConsignor, partyConsignee, party, dangerousGoods, cashOnDelivery, charges, insurance, equipment, auditLog, consignmentEvent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Consignment {\n");
    sb.append("    consignmentNo: ").append(toIndentedString(consignmentNo)).append("\n");
    sb.append("    consignmentNoType: ").append(toIndentedString(consignmentNoType)).append("\n");
    sb.append("    consignmentNoIdentifier: ").append(toIndentedString(consignmentNoIdentifier)).append("\n");
    sb.append("    consignmentNoIssuer: ").append(toIndentedString(consignmentNoIssuer)).append("\n");
    sb.append("    consignmentMaster: ").append(toIndentedString(consignmentMaster)).append("\n");
    sb.append("    productCode: ").append(toIndentedString(productCode)).append("\n");
    sb.append("    serviceGroup: ").append(toIndentedString(serviceGroup)).append("\n");
    sb.append("    termsOfDeliver: ").append(toIndentedString(termsOfDeliver)).append("\n");
    sb.append("    numberOfPackages: ").append(toIndentedString(numberOfPackages)).append("\n");
    sb.append("    netWeight: ").append(toIndentedString(netWeight)).append("\n");
    sb.append("    grossWeight: ").append(toIndentedString(grossWeight)).append("\n");
    sb.append("    grossVolume: ").append(toIndentedString(grossVolume)).append("\n");
    sb.append("    loadingMetres: ").append(toIndentedString(loadingMetres)).append("\n");
    sb.append("    palletFootprints: ").append(toIndentedString(palletFootprints)).append("\n");
    sb.append("    goodsDescription: ").append(toIndentedString(goodsDescription)).append("\n");
    sb.append("    dgsTotalPoints: ").append(toIndentedString(dgsTotalPoints)).append("\n");
    sb.append("    termsType: ").append(toIndentedString(termsType)).append("\n");
    sb.append("    termsCode: ").append(toIndentedString(termsCode)).append("\n");
    sb.append("    termsLocation: ").append(toIndentedString(termsLocation)).append("\n");
    sb.append("    temperatureTransportMin: ").append(toIndentedString(temperatureTransportMin)).append("\n");
    sb.append("    temperatureTransportMax: ").append(toIndentedString(temperatureTransportMax)).append("\n");
    sb.append("    temperatureStorageMin: ").append(toIndentedString(temperatureStorageMin)).append("\n");
    sb.append("    temperatureStorageMax: ").append(toIndentedString(temperatureStorageMax)).append("\n");
    sb.append("    agreedDiscount: ").append(toIndentedString(agreedDiscount)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    discountRegisteredBy: ").append(toIndentedString(discountRegisteredBy)).append("\n");
    sb.append("    bookingReference: ").append(toIndentedString(bookingReference)).append("\n");
    sb.append("    syntheticStatus: ").append(toIndentedString(syntheticStatus)).append("\n");
    sb.append("    receiverReference: ").append(toIndentedString(receiverReference)).append("\n");
    sb.append("    vas: ").append(toIndentedString(vas)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    freeText: ").append(toIndentedString(freeText)).append("\n");
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("    trackingRecipients: ").append(toIndentedString(trackingRecipients)).append("\n");
    sb.append("    partyConsignor: ").append(toIndentedString(partyConsignor)).append("\n");
    sb.append("    partyConsignee: ").append(toIndentedString(partyConsignee)).append("\n");
    sb.append("    party: ").append(toIndentedString(party)).append("\n");
    sb.append("    dangerousGoods: ").append(toIndentedString(dangerousGoods)).append("\n");
    sb.append("    cashOnDelivery: ").append(toIndentedString(cashOnDelivery)).append("\n");
    sb.append("    charges: ").append(toIndentedString(charges)).append("\n");
    sb.append("    insurance: ").append(toIndentedString(insurance)).append("\n");
    sb.append("    equipment: ").append(toIndentedString(equipment)).append("\n");
    sb.append("    auditLog: ").append(toIndentedString(auditLog)).append("\n");
    sb.append("    consignmentEvent: ").append(toIndentedString(consignmentEvent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

