/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Coordinates
 */
@JsonPropertyOrder({
  Coordinates.JSON_PROPERTY_X_COORDINATE,
  Coordinates.JSON_PROPERTY_Y_COORDINATE,
  Coordinates.JSON_PROPERTY_COORDINATE_SYSTEM,
  Coordinates.JSON_PROPERTY_LOCATION
})
@JsonTypeName("coordinates")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class Coordinates {
  public static final String JSON_PROPERTY_X_COORDINATE = "xCoordinate";
  private String xCoordinate;

  public static final String JSON_PROPERTY_Y_COORDINATE = "yCoordinate";
  private String yCoordinate;

  public static final String JSON_PROPERTY_COORDINATE_SYSTEM = "coordinateSystem";
  private String coordinateSystem;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private String location;


  public Coordinates xCoordinate(String xCoordinate) {
    
    this.xCoordinate = xCoordinate;
    return this;
  }

   /**
   * Get xCoordinate
   * @return xCoordinate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_X_COORDINATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getxCoordinate() {
    return xCoordinate;
  }


  public void setxCoordinate(String xCoordinate) {
    this.xCoordinate = xCoordinate;
  }


  public Coordinates yCoordinate(String yCoordinate) {
    
    this.yCoordinate = yCoordinate;
    return this;
  }

   /**
   * Get yCoordinate
   * @return yCoordinate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_Y_COORDINATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getyCoordinate() {
    return yCoordinate;
  }


  public void setyCoordinate(String yCoordinate) {
    this.yCoordinate = yCoordinate;
  }


  public Coordinates coordinateSystem(String coordinateSystem) {
    
    this.coordinateSystem = coordinateSystem;
    return this;
  }

   /**
   * Get coordinateSystem
   * @return coordinateSystem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COORDINATE_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCoordinateSystem() {
    return coordinateSystem;
  }


  public void setCoordinateSystem(String coordinateSystem) {
    this.coordinateSystem = coordinateSystem;
  }


  public Coordinates location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Coordinates coordinates = (Coordinates) o;
    return Objects.equals(this.xCoordinate, coordinates.xCoordinate) &&
        Objects.equals(this.yCoordinate, coordinates.yCoordinate) &&
        Objects.equals(this.coordinateSystem, coordinates.coordinateSystem) &&
        Objects.equals(this.location, coordinates.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(xCoordinate, yCoordinate, coordinateSystem, location);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Coordinates {\n");
    sb.append("    xCoordinate: ").append(toIndentedString(xCoordinate)).append("\n");
    sb.append("    yCoordinate: ").append(toIndentedString(yCoordinate)).append("\n");
    sb.append("    coordinateSystem: ").append(toIndentedString(coordinateSystem)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

