/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DangerousGoods
 */
@JsonPropertyOrder({
  DangerousGoods.JSON_PROPERTY_REGULATION_CODE,
  DangerousGoods.JSON_PROPERTY_HAZARD_CODE,
  DangerousGoods.JSON_PROPERTY_ADDITIONAL_HAZARD_CODE,
  DangerousGoods.JSON_PROPERTY_UN_NO,
  DangerousGoods.JSON_PROPERTY_PACKAGING,
  DangerousGoods.JSON_PROPERTY_TUNNEL_RESTRICTIONS,
  DangerousGoods.JSON_PROPERTY_TECH_NAME,
  DangerousGoods.JSON_PROPERTY_NET_WEIGHT_KG,
  DangerousGoods.JSON_PROPERTY_NET_VOLUME_LITRE,
  DangerousGoods.JSON_PROPERTY_HAZARDOUS_GOODS_POINTS
})
@JsonTypeName("dangerousGoods")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class DangerousGoods {
  public static final String JSON_PROPERTY_REGULATION_CODE = "regulationCode";
  private String regulationCode;

  public static final String JSON_PROPERTY_HAZARD_CODE = "hazardCode";
  private String hazardCode;

  public static final String JSON_PROPERTY_ADDITIONAL_HAZARD_CODE = "additionalHazardCode";
  private String additionalHazardCode;

  public static final String JSON_PROPERTY_UN_NO = "unNo";
  private Integer unNo;

  public static final String JSON_PROPERTY_PACKAGING = "packaging";
  private String packaging;

  public static final String JSON_PROPERTY_TUNNEL_RESTRICTIONS = "tunnelRestrictions";
  private String tunnelRestrictions;

  public static final String JSON_PROPERTY_TECH_NAME = "techName";
  private String techName;

  public static final String JSON_PROPERTY_NET_WEIGHT_KG = "netWeightKg";
  private Long netWeightKg;

  public static final String JSON_PROPERTY_NET_VOLUME_LITRE = "netVolumeLitre";
  private Long netVolumeLitre;

  public static final String JSON_PROPERTY_HAZARDOUS_GOODS_POINTS = "hazardousGoodsPoints";
  private Integer hazardousGoodsPoints;


  public DangerousGoods regulationCode(String regulationCode) {
    
    this.regulationCode = regulationCode;
    return this;
  }

   /**
   * Get regulationCode
   * @return regulationCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REGULATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegulationCode() {
    return regulationCode;
  }


  public void setRegulationCode(String regulationCode) {
    this.regulationCode = regulationCode;
  }


  public DangerousGoods hazardCode(String hazardCode) {
    
    this.hazardCode = hazardCode;
    return this;
  }

   /**
   * Get hazardCode
   * @return hazardCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HAZARD_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHazardCode() {
    return hazardCode;
  }


  public void setHazardCode(String hazardCode) {
    this.hazardCode = hazardCode;
  }


  public DangerousGoods additionalHazardCode(String additionalHazardCode) {
    
    this.additionalHazardCode = additionalHazardCode;
    return this;
  }

   /**
   * Get additionalHazardCode
   * @return additionalHazardCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_HAZARD_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalHazardCode() {
    return additionalHazardCode;
  }


  public void setAdditionalHazardCode(String additionalHazardCode) {
    this.additionalHazardCode = additionalHazardCode;
  }


  public DangerousGoods unNo(Integer unNo) {
    
    this.unNo = unNo;
    return this;
  }

   /**
   * Get unNo
   * @return unNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UN_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUnNo() {
    return unNo;
  }


  public void setUnNo(Integer unNo) {
    this.unNo = unNo;
  }


  public DangerousGoods packaging(String packaging) {
    
    this.packaging = packaging;
    return this;
  }

   /**
   * Get packaging
   * @return packaging
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PACKAGING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPackaging() {
    return packaging;
  }


  public void setPackaging(String packaging) {
    this.packaging = packaging;
  }


  public DangerousGoods tunnelRestrictions(String tunnelRestrictions) {
    
    this.tunnelRestrictions = tunnelRestrictions;
    return this;
  }

   /**
   * Get tunnelRestrictions
   * @return tunnelRestrictions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TUNNEL_RESTRICTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTunnelRestrictions() {
    return tunnelRestrictions;
  }


  public void setTunnelRestrictions(String tunnelRestrictions) {
    this.tunnelRestrictions = tunnelRestrictions;
  }


  public DangerousGoods techName(String techName) {
    
    this.techName = techName;
    return this;
  }

   /**
   * Get techName
   * @return techName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TECH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTechName() {
    return techName;
  }


  public void setTechName(String techName) {
    this.techName = techName;
  }


  public DangerousGoods netWeightKg(Long netWeightKg) {
    
    this.netWeightKg = netWeightKg;
    return this;
  }

   /**
   * Get netWeightKg
   * @return netWeightKg
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NET_WEIGHT_KG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNetWeightKg() {
    return netWeightKg;
  }


  public void setNetWeightKg(Long netWeightKg) {
    this.netWeightKg = netWeightKg;
  }


  public DangerousGoods netVolumeLitre(Long netVolumeLitre) {
    
    this.netVolumeLitre = netVolumeLitre;
    return this;
  }

   /**
   * Get netVolumeLitre
   * @return netVolumeLitre
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NET_VOLUME_LITRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNetVolumeLitre() {
    return netVolumeLitre;
  }


  public void setNetVolumeLitre(Long netVolumeLitre) {
    this.netVolumeLitre = netVolumeLitre;
  }


  public DangerousGoods hazardousGoodsPoints(Integer hazardousGoodsPoints) {
    
    this.hazardousGoodsPoints = hazardousGoodsPoints;
    return this;
  }

   /**
   * Get hazardousGoodsPoints
   * @return hazardousGoodsPoints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HAZARDOUS_GOODS_POINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHazardousGoodsPoints() {
    return hazardousGoodsPoints;
  }


  public void setHazardousGoodsPoints(Integer hazardousGoodsPoints) {
    this.hazardousGoodsPoints = hazardousGoodsPoints;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DangerousGoods dangerousGoods = (DangerousGoods) o;
    return Objects.equals(this.regulationCode, dangerousGoods.regulationCode) &&
        Objects.equals(this.hazardCode, dangerousGoods.hazardCode) &&
        Objects.equals(this.additionalHazardCode, dangerousGoods.additionalHazardCode) &&
        Objects.equals(this.unNo, dangerousGoods.unNo) &&
        Objects.equals(this.packaging, dangerousGoods.packaging) &&
        Objects.equals(this.tunnelRestrictions, dangerousGoods.tunnelRestrictions) &&
        Objects.equals(this.techName, dangerousGoods.techName) &&
        Objects.equals(this.netWeightKg, dangerousGoods.netWeightKg) &&
        Objects.equals(this.netVolumeLitre, dangerousGoods.netVolumeLitre) &&
        Objects.equals(this.hazardousGoodsPoints, dangerousGoods.hazardousGoodsPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regulationCode, hazardCode, additionalHazardCode, unNo, packaging, tunnelRestrictions, techName, netWeightKg, netVolumeLitre, hazardousGoodsPoints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DangerousGoods {\n");
    sb.append("    regulationCode: ").append(toIndentedString(regulationCode)).append("\n");
    sb.append("    hazardCode: ").append(toIndentedString(hazardCode)).append("\n");
    sb.append("    additionalHazardCode: ").append(toIndentedString(additionalHazardCode)).append("\n");
    sb.append("    unNo: ").append(toIndentedString(unNo)).append("\n");
    sb.append("    packaging: ").append(toIndentedString(packaging)).append("\n");
    sb.append("    tunnelRestrictions: ").append(toIndentedString(tunnelRestrictions)).append("\n");
    sb.append("    techName: ").append(toIndentedString(techName)).append("\n");
    sb.append("    netWeightKg: ").append(toIndentedString(netWeightKg)).append("\n");
    sb.append("    netVolumeLitre: ").append(toIndentedString(netVolumeLitre)).append("\n");
    sb.append("    hazardousGoodsPoints: ").append(toIndentedString(hazardousGoodsPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

