/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Equipment
 */
@JsonPropertyOrder({
  Equipment.JSON_PROPERTY_EQUIPMENT_TYPE,
  Equipment.JSON_PROPERTY_EQUIPMENT_QUANTITY
})
@JsonTypeName("equipment")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class Equipment {
  public static final String JSON_PROPERTY_EQUIPMENT_TYPE = "equipmentType";
  private String equipmentType;

  public static final String JSON_PROPERTY_EQUIPMENT_QUANTITY = "equipmentQuantity";
  private BigDecimal equipmentQuantity;


  public Equipment equipmentType(String equipmentType) {
    
    this.equipmentType = equipmentType;
    return this;
  }

   /**
   * Get equipmentType
   * @return equipmentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EQUIPMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEquipmentType() {
    return equipmentType;
  }


  public void setEquipmentType(String equipmentType) {
    this.equipmentType = equipmentType;
  }


  public Equipment equipmentQuantity(BigDecimal equipmentQuantity) {
    
    this.equipmentQuantity = equipmentQuantity;
    return this;
  }

   /**
   * Get equipmentQuantity
   * @return equipmentQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EQUIPMENT_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getEquipmentQuantity() {
    return equipmentQuantity;
  }


  public void setEquipmentQuantity(BigDecimal equipmentQuantity) {
    this.equipmentQuantity = equipmentQuantity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Equipment equipment = (Equipment) o;
    return Objects.equals(this.equipmentType, equipment.equipmentType) &&
        Objects.equals(this.equipmentQuantity, equipment.equipmentQuantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(equipmentType, equipmentQuantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Equipment {\n");
    sb.append("    equipmentType: ").append(toIndentedString(equipmentType)).append("\n");
    sb.append("    equipmentQuantity: ").append(toIndentedString(equipmentQuantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

