/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Insurance
 */
@JsonPropertyOrder({
  Insurance.JSON_PROPERTY_GOODS_DESCRIPTION,
  Insurance.JSON_PROPERTY_INSURED_AMOUNT,
  Insurance.JSON_PROPERTY_INSURED_AMOUNT_CURRENCY
})
@JsonTypeName("insurance")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class Insurance {
  public static final String JSON_PROPERTY_GOODS_DESCRIPTION = "goodsDescription";
  private String goodsDescription;

  public static final String JSON_PROPERTY_INSURED_AMOUNT = "insuredAmount";
  private BigDecimal insuredAmount;

  public static final String JSON_PROPERTY_INSURED_AMOUNT_CURRENCY = "insuredAmountCurrency";
  private String insuredAmountCurrency;


  public Insurance goodsDescription(String goodsDescription) {
    
    this.goodsDescription = goodsDescription;
    return this;
  }

   /**
   * Get goodsDescription
   * @return goodsDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GOODS_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGoodsDescription() {
    return goodsDescription;
  }


  public void setGoodsDescription(String goodsDescription) {
    this.goodsDescription = goodsDescription;
  }


  public Insurance insuredAmount(BigDecimal insuredAmount) {
    
    this.insuredAmount = insuredAmount;
    return this;
  }

   /**
   * Get insuredAmount
   * @return insuredAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INSURED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getInsuredAmount() {
    return insuredAmount;
  }


  public void setInsuredAmount(BigDecimal insuredAmount) {
    this.insuredAmount = insuredAmount;
  }


  public Insurance insuredAmountCurrency(String insuredAmountCurrency) {
    
    this.insuredAmountCurrency = insuredAmountCurrency;
    return this;
  }

   /**
   * Get insuredAmountCurrency
   * @return insuredAmountCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INSURED_AMOUNT_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInsuredAmountCurrency() {
    return insuredAmountCurrency;
  }


  public void setInsuredAmountCurrency(String insuredAmountCurrency) {
    this.insuredAmountCurrency = insuredAmountCurrency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Insurance insurance = (Insurance) o;
    return Objects.equals(this.goodsDescription, insurance.goodsDescription) &&
        Objects.equals(this.insuredAmount, insurance.insuredAmount) &&
        Objects.equals(this.insuredAmountCurrency, insurance.insuredAmountCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(goodsDescription, insuredAmount, insuredAmountCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Insurance {\n");
    sb.append("    goodsDescription: ").append(toIndentedString(goodsDescription)).append("\n");
    sb.append("    insuredAmount: ").append(toIndentedString(insuredAmount)).append("\n");
    sb.append("    insuredAmountCurrency: ").append(toIndentedString(insuredAmountCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

