/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import no.posten.ph.consignment.model.DeliveryAddress;
import no.posten.ph.consignment.model.PostalAddress;
import no.posten.ph.consignment.model.Reference;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PartyConsignee
 */
@JsonPropertyOrder({
  PartyConsignee.JSON_PROPERTY_NAME,
  PartyConsignee.JSON_PROPERTY_SOUNDEX_NAME,
  PartyConsignee.JSON_PROPERTY_ACTOR_NO,
  PartyConsignee.JSON_PROPERTY_SYSTEM,
  PartyConsignee.JSON_PROPERTY_PARTY_ID,
  PartyConsignee.JSON_PROPERTY_SUBPARTY_ID,
  PartyConsignee.JSON_PROPERTY_ID_CODE_LIST,
  PartyConsignee.JSON_PROPERTY_FUNCTION,
  PartyConsignee.JSON_PROPERTY_PHONE,
  PartyConsignee.JSON_PROPERTY_MOBILE,
  PartyConsignee.JSON_PROPERTY_TELEFAX,
  PartyConsignee.JSON_PROPERTY_EMAIL,
  PartyConsignee.JSON_PROPERTY_URL,
  PartyConsignee.JSON_PROPERTY_DIGIPOST_ID,
  PartyConsignee.JSON_PROPERTY_PERSONAL_ALIAS,
  PartyConsignee.JSON_PROPERTY_CREATED_PROGRAM_ID,
  PartyConsignee.JSON_PROPERTY_CREATED_TIMESTAMP,
  PartyConsignee.JSON_PROPERTY_MODIFIED_PROGRAM_ID,
  PartyConsignee.JSON_PROPERTY_MODIFIED_TIMESTAMP,
  PartyConsignee.JSON_PROPERTY_POSTAL_ADDRESS,
  PartyConsignee.JSON_PROPERTY_DELIVERY_ADDRESS,
  PartyConsignee.JSON_PROPERTY_REFERENCE
})
@JsonTypeName("partyConsignee")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class PartyConsignee {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_SOUNDEX_NAME = "soundexName";
  private String soundexName;

  public static final String JSON_PROPERTY_ACTOR_NO = "actorNo";
  private String actorNo;

  public static final String JSON_PROPERTY_SYSTEM = "system";
  private String system;

  public static final String JSON_PROPERTY_PARTY_ID = "partyId";
  private String partyId;

  public static final String JSON_PROPERTY_SUBPARTY_ID = "subpartyId";
  private String subpartyId;

  public static final String JSON_PROPERTY_ID_CODE_LIST = "idCodeList";
  private String idCodeList;

  public static final String JSON_PROPERTY_FUNCTION = "function";
  private String function;

  public static final String JSON_PROPERTY_PHONE = "phone";
  private String phone;

  public static final String JSON_PROPERTY_MOBILE = "mobile";
  private String mobile;

  public static final String JSON_PROPERTY_TELEFAX = "telefax";
  private String telefax;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_DIGIPOST_ID = "digipostId";
  private String digipostId;

  public static final String JSON_PROPERTY_PERSONAL_ALIAS = "personalAlias";
  private String personalAlias;

  public static final String JSON_PROPERTY_CREATED_PROGRAM_ID = "createdProgramId";
  private String createdProgramId;

  public static final String JSON_PROPERTY_CREATED_TIMESTAMP = "createdTimestamp";
  private OffsetDateTime createdTimestamp;

  public static final String JSON_PROPERTY_MODIFIED_PROGRAM_ID = "modifiedProgramId";
  private String modifiedProgramId;

  public static final String JSON_PROPERTY_MODIFIED_TIMESTAMP = "modifiedTimestamp";
  private OffsetDateTime modifiedTimestamp;

  public static final String JSON_PROPERTY_POSTAL_ADDRESS = "postalAddress";
  private PostalAddress postalAddress;

  public static final String JSON_PROPERTY_DELIVERY_ADDRESS = "deliveryAddress";
  private DeliveryAddress deliveryAddress;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  private List<Reference> reference = null;


  public PartyConsignee name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public PartyConsignee soundexName(String soundexName) {
    
    this.soundexName = soundexName;
    return this;
  }

   /**
   * Get soundexName
   * @return soundexName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOUNDEX_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSoundexName() {
    return soundexName;
  }


  public void setSoundexName(String soundexName) {
    this.soundexName = soundexName;
  }


  public PartyConsignee actorNo(String actorNo) {
    
    this.actorNo = actorNo;
    return this;
  }

   /**
   * Get actorNo
   * @return actorNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTOR_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getActorNo() {
    return actorNo;
  }


  public void setActorNo(String actorNo) {
    this.actorNo = actorNo;
  }


  public PartyConsignee system(String system) {
    
    this.system = system;
    return this;
  }

   /**
   * Get system
   * @return system
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSystem() {
    return system;
  }


  public void setSystem(String system) {
    this.system = system;
  }


  public PartyConsignee partyId(String partyId) {
    
    this.partyId = partyId;
    return this;
  }

   /**
   * Get partyId
   * @return partyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPartyId() {
    return partyId;
  }


  public void setPartyId(String partyId) {
    this.partyId = partyId;
  }


  public PartyConsignee subpartyId(String subpartyId) {
    
    this.subpartyId = subpartyId;
    return this;
  }

   /**
   * Get subpartyId
   * @return subpartyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBPARTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubpartyId() {
    return subpartyId;
  }


  public void setSubpartyId(String subpartyId) {
    this.subpartyId = subpartyId;
  }


  public PartyConsignee idCodeList(String idCodeList) {
    
    this.idCodeList = idCodeList;
    return this;
  }

   /**
   * Get idCodeList
   * @return idCodeList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID_CODE_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdCodeList() {
    return idCodeList;
  }


  public void setIdCodeList(String idCodeList) {
    this.idCodeList = idCodeList;
  }


  public PartyConsignee function(String function) {
    
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunction() {
    return function;
  }


  public void setFunction(String function) {
    this.function = function;
  }


  public PartyConsignee phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


  public PartyConsignee mobile(String mobile) {
    
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MOBILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMobile() {
    return mobile;
  }


  public void setMobile(String mobile) {
    this.mobile = mobile;
  }


  public PartyConsignee telefax(String telefax) {
    
    this.telefax = telefax;
    return this;
  }

   /**
   * Get telefax
   * @return telefax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TELEFAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTelefax() {
    return telefax;
  }


  public void setTelefax(String telefax) {
    this.telefax = telefax;
  }


  public PartyConsignee email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public PartyConsignee url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public PartyConsignee digipostId(String digipostId) {
    
    this.digipostId = digipostId;
    return this;
  }

   /**
   * Get digipostId
   * @return digipostId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DIGIPOST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDigipostId() {
    return digipostId;
  }


  public void setDigipostId(String digipostId) {
    this.digipostId = digipostId;
  }


  public PartyConsignee personalAlias(String personalAlias) {
    
    this.personalAlias = personalAlias;
    return this;
  }

   /**
   * Get personalAlias
   * @return personalAlias
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PERSONAL_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPersonalAlias() {
    return personalAlias;
  }


  public void setPersonalAlias(String personalAlias) {
    this.personalAlias = personalAlias;
  }


  public PartyConsignee createdProgramId(String createdProgramId) {
    
    this.createdProgramId = createdProgramId;
    return this;
  }

   /**
   * Get createdProgramId
   * @return createdProgramId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_PROGRAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedProgramId() {
    return createdProgramId;
  }


  public void setCreatedProgramId(String createdProgramId) {
    this.createdProgramId = createdProgramId;
  }


  public PartyConsignee createdTimestamp(OffsetDateTime createdTimestamp) {
    
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * Get createdTimestamp
   * @return createdTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedTimestamp() {
    return createdTimestamp;
  }


  public void setCreatedTimestamp(OffsetDateTime createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public PartyConsignee modifiedProgramId(String modifiedProgramId) {
    
    this.modifiedProgramId = modifiedProgramId;
    return this;
  }

   /**
   * Get modifiedProgramId
   * @return modifiedProgramId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MODIFIED_PROGRAM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModifiedProgramId() {
    return modifiedProgramId;
  }


  public void setModifiedProgramId(String modifiedProgramId) {
    this.modifiedProgramId = modifiedProgramId;
  }


  public PartyConsignee modifiedTimestamp(OffsetDateTime modifiedTimestamp) {
    
    this.modifiedTimestamp = modifiedTimestamp;
    return this;
  }

   /**
   * Get modifiedTimestamp
   * @return modifiedTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MODIFIED_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getModifiedTimestamp() {
    return modifiedTimestamp;
  }


  public void setModifiedTimestamp(OffsetDateTime modifiedTimestamp) {
    this.modifiedTimestamp = modifiedTimestamp;
  }


  public PartyConsignee postalAddress(PostalAddress postalAddress) {
    
    this.postalAddress = postalAddress;
    return this;
  }

   /**
   * Get postalAddress
   * @return postalAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POSTAL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostalAddress getPostalAddress() {
    return postalAddress;
  }


  public void setPostalAddress(PostalAddress postalAddress) {
    this.postalAddress = postalAddress;
  }


  public PartyConsignee deliveryAddress(DeliveryAddress deliveryAddress) {
    
    this.deliveryAddress = deliveryAddress;
    return this;
  }

   /**
   * Get deliveryAddress
   * @return deliveryAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELIVERY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeliveryAddress getDeliveryAddress() {
    return deliveryAddress;
  }


  public void setDeliveryAddress(DeliveryAddress deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
  }


  public PartyConsignee reference(List<Reference> reference) {
    
    this.reference = reference;
    return this;
  }

  public PartyConsignee addReferenceItem(Reference referenceItem) {
    if (this.reference == null) {
      this.reference = new ArrayList<>();
    }
    this.reference.add(referenceItem);
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Reference> getReference() {
    return reference;
  }


  public void setReference(List<Reference> reference) {
    this.reference = reference;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartyConsignee partyConsignee = (PartyConsignee) o;
    return Objects.equals(this.name, partyConsignee.name) &&
        Objects.equals(this.soundexName, partyConsignee.soundexName) &&
        Objects.equals(this.actorNo, partyConsignee.actorNo) &&
        Objects.equals(this.system, partyConsignee.system) &&
        Objects.equals(this.partyId, partyConsignee.partyId) &&
        Objects.equals(this.subpartyId, partyConsignee.subpartyId) &&
        Objects.equals(this.idCodeList, partyConsignee.idCodeList) &&
        Objects.equals(this.function, partyConsignee.function) &&
        Objects.equals(this.phone, partyConsignee.phone) &&
        Objects.equals(this.mobile, partyConsignee.mobile) &&
        Objects.equals(this.telefax, partyConsignee.telefax) &&
        Objects.equals(this.email, partyConsignee.email) &&
        Objects.equals(this.url, partyConsignee.url) &&
        Objects.equals(this.digipostId, partyConsignee.digipostId) &&
        Objects.equals(this.personalAlias, partyConsignee.personalAlias) &&
        Objects.equals(this.createdProgramId, partyConsignee.createdProgramId) &&
        Objects.equals(this.createdTimestamp, partyConsignee.createdTimestamp) &&
        Objects.equals(this.modifiedProgramId, partyConsignee.modifiedProgramId) &&
        Objects.equals(this.modifiedTimestamp, partyConsignee.modifiedTimestamp) &&
        Objects.equals(this.postalAddress, partyConsignee.postalAddress) &&
        Objects.equals(this.deliveryAddress, partyConsignee.deliveryAddress) &&
        Objects.equals(this.reference, partyConsignee.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, soundexName, actorNo, system, partyId, subpartyId, idCodeList, function, phone, mobile, telefax, email, url, digipostId, personalAlias, createdProgramId, createdTimestamp, modifiedProgramId, modifiedTimestamp, postalAddress, deliveryAddress, reference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartyConsignee {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    soundexName: ").append(toIndentedString(soundexName)).append("\n");
    sb.append("    actorNo: ").append(toIndentedString(actorNo)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
    sb.append("    subpartyId: ").append(toIndentedString(subpartyId)).append("\n");
    sb.append("    idCodeList: ").append(toIndentedString(idCodeList)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    telefax: ").append(toIndentedString(telefax)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    digipostId: ").append(toIndentedString(digipostId)).append("\n");
    sb.append("    personalAlias: ").append(toIndentedString(personalAlias)).append("\n");
    sb.append("    createdProgramId: ").append(toIndentedString(createdProgramId)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    modifiedProgramId: ").append(toIndentedString(modifiedProgramId)).append("\n");
    sb.append("    modifiedTimestamp: ").append(toIndentedString(modifiedTimestamp)).append("\n");
    sb.append("    postalAddress: ").append(toIndentedString(postalAddress)).append("\n");
    sb.append("    deliveryAddress: ").append(toIndentedString(deliveryAddress)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

