/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * RbtInformation
 */
@JsonPropertyOrder({
  RbtInformation.JSON_PROPERTY_ROUTE_ID,
  RbtInformation.JSON_PROPERTY_TRIP_ID,
  RbtInformation.JSON_PROPERTY_STOP_ID,
  RbtInformation.JSON_PROPERTY_PLAN_ID,
  RbtInformation.JSON_PROPERTY_AREA_ID,
  RbtInformation.JSON_PROPERTY_LOCATION_ID,
  RbtInformation.JSON_PROPERTY_DRIVER_ID,
  RbtInformation.JSON_PROPERTY_TRUCK_ID,
  RbtInformation.JSON_PROPERTY_LOGICAL_LOADCARRIER_ID,
  RbtInformation.JSON_PROPERTY_PHYSICAL_LOADCARRIER_ID,
  RbtInformation.JSON_PROPERTY_LOADCARRIER_EXTERNAL_ID,
  RbtInformation.JSON_PROPERTY_FLEX_FIELD,
  RbtInformation.JSON_PROPERTY_COMBINATION_TRIP_ID,
  RbtInformation.JSON_PROPERTY_TELEPHONE_NUMBER,
  RbtInformation.JSON_PROPERTY_TMS_OPERATION_ID
})
@JsonTypeName("rbtInformation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class RbtInformation {
  public static final String JSON_PROPERTY_ROUTE_ID = "routeId";
  private String routeId;

  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  private String tripId;

  public static final String JSON_PROPERTY_STOP_ID = "stopId";
  private String stopId;

  public static final String JSON_PROPERTY_PLAN_ID = "planId";
  private String planId;

  public static final String JSON_PROPERTY_AREA_ID = "areaId";
  private String areaId;

  public static final String JSON_PROPERTY_LOCATION_ID = "locationId";
  private String locationId;

  public static final String JSON_PROPERTY_DRIVER_ID = "driverId";
  private String driverId;

  public static final String JSON_PROPERTY_TRUCK_ID = "truckId";
  private String truckId;

  public static final String JSON_PROPERTY_LOGICAL_LOADCARRIER_ID = "logicalLoadcarrierId";
  private String logicalLoadcarrierId;

  public static final String JSON_PROPERTY_PHYSICAL_LOADCARRIER_ID = "physicalLoadcarrierId";
  private String physicalLoadcarrierId;

  public static final String JSON_PROPERTY_LOADCARRIER_EXTERNAL_ID = "loadcarrierExternalId";
  private String loadcarrierExternalId;

  public static final String JSON_PROPERTY_FLEX_FIELD = "flexField";
  private String flexField;

  public static final String JSON_PROPERTY_COMBINATION_TRIP_ID = "combinationTripId";
  private String combinationTripId;

  public static final String JSON_PROPERTY_TELEPHONE_NUMBER = "telephoneNumber";
  private String telephoneNumber;

  public static final String JSON_PROPERTY_TMS_OPERATION_ID = "tmsOperationId";
  private String tmsOperationId;


  public RbtInformation routeId(String routeId) {
    
    this.routeId = routeId;
    return this;
  }

   /**
   * Get routeId
   * @return routeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROUTE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRouteId() {
    return routeId;
  }


  public void setRouteId(String routeId) {
    this.routeId = routeId;
  }


  public RbtInformation tripId(String tripId) {
    
    this.tripId = tripId;
    return this;
  }

   /**
   * Get tripId
   * @return tripId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTripId() {
    return tripId;
  }


  public void setTripId(String tripId) {
    this.tripId = tripId;
  }


  public RbtInformation stopId(String stopId) {
    
    this.stopId = stopId;
    return this;
  }

   /**
   * Get stopId
   * @return stopId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STOP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStopId() {
    return stopId;
  }


  public void setStopId(String stopId) {
    this.stopId = stopId;
  }


  public RbtInformation planId(String planId) {
    
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PLAN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlanId() {
    return planId;
  }


  public void setPlanId(String planId) {
    this.planId = planId;
  }


  public RbtInformation areaId(String areaId) {
    
    this.areaId = areaId;
    return this;
  }

   /**
   * Get areaId
   * @return areaId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AREA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAreaId() {
    return areaId;
  }


  public void setAreaId(String areaId) {
    this.areaId = areaId;
  }


  public RbtInformation locationId(String locationId) {
    
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocationId() {
    return locationId;
  }


  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }


  public RbtInformation driverId(String driverId) {
    
    this.driverId = driverId;
    return this;
  }

   /**
   * Get driverId
   * @return driverId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DRIVER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDriverId() {
    return driverId;
  }


  public void setDriverId(String driverId) {
    this.driverId = driverId;
  }


  public RbtInformation truckId(String truckId) {
    
    this.truckId = truckId;
    return this;
  }

   /**
   * Get truckId
   * @return truckId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRUCK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTruckId() {
    return truckId;
  }


  public void setTruckId(String truckId) {
    this.truckId = truckId;
  }


  public RbtInformation logicalLoadcarrierId(String logicalLoadcarrierId) {
    
    this.logicalLoadcarrierId = logicalLoadcarrierId;
    return this;
  }

   /**
   * Get logicalLoadcarrierId
   * @return logicalLoadcarrierId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOGICAL_LOADCARRIER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogicalLoadcarrierId() {
    return logicalLoadcarrierId;
  }


  public void setLogicalLoadcarrierId(String logicalLoadcarrierId) {
    this.logicalLoadcarrierId = logicalLoadcarrierId;
  }


  public RbtInformation physicalLoadcarrierId(String physicalLoadcarrierId) {
    
    this.physicalLoadcarrierId = physicalLoadcarrierId;
    return this;
  }

   /**
   * Get physicalLoadcarrierId
   * @return physicalLoadcarrierId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PHYSICAL_LOADCARRIER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhysicalLoadcarrierId() {
    return physicalLoadcarrierId;
  }


  public void setPhysicalLoadcarrierId(String physicalLoadcarrierId) {
    this.physicalLoadcarrierId = physicalLoadcarrierId;
  }


  public RbtInformation loadcarrierExternalId(String loadcarrierExternalId) {
    
    this.loadcarrierExternalId = loadcarrierExternalId;
    return this;
  }

   /**
   * Get loadcarrierExternalId
   * @return loadcarrierExternalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOADCARRIER_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoadcarrierExternalId() {
    return loadcarrierExternalId;
  }


  public void setLoadcarrierExternalId(String loadcarrierExternalId) {
    this.loadcarrierExternalId = loadcarrierExternalId;
  }


  public RbtInformation flexField(String flexField) {
    
    this.flexField = flexField;
    return this;
  }

   /**
   * Get flexField
   * @return flexField
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FLEX_FIELD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlexField() {
    return flexField;
  }


  public void setFlexField(String flexField) {
    this.flexField = flexField;
  }


  public RbtInformation combinationTripId(String combinationTripId) {
    
    this.combinationTripId = combinationTripId;
    return this;
  }

   /**
   * Get combinationTripId
   * @return combinationTripId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COMBINATION_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCombinationTripId() {
    return combinationTripId;
  }


  public void setCombinationTripId(String combinationTripId) {
    this.combinationTripId = combinationTripId;
  }


  public RbtInformation telephoneNumber(String telephoneNumber) {
    
    this.telephoneNumber = telephoneNumber;
    return this;
  }

   /**
   * Get telephoneNumber
   * @return telephoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TELEPHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTelephoneNumber() {
    return telephoneNumber;
  }


  public void setTelephoneNumber(String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
  }


  public RbtInformation tmsOperationId(String tmsOperationId) {
    
    this.tmsOperationId = tmsOperationId;
    return this;
  }

   /**
   * Get tmsOperationId
   * @return tmsOperationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TMS_OPERATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTmsOperationId() {
    return tmsOperationId;
  }


  public void setTmsOperationId(String tmsOperationId) {
    this.tmsOperationId = tmsOperationId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RbtInformation rbtInformation = (RbtInformation) o;
    return Objects.equals(this.routeId, rbtInformation.routeId) &&
        Objects.equals(this.tripId, rbtInformation.tripId) &&
        Objects.equals(this.stopId, rbtInformation.stopId) &&
        Objects.equals(this.planId, rbtInformation.planId) &&
        Objects.equals(this.areaId, rbtInformation.areaId) &&
        Objects.equals(this.locationId, rbtInformation.locationId) &&
        Objects.equals(this.driverId, rbtInformation.driverId) &&
        Objects.equals(this.truckId, rbtInformation.truckId) &&
        Objects.equals(this.logicalLoadcarrierId, rbtInformation.logicalLoadcarrierId) &&
        Objects.equals(this.physicalLoadcarrierId, rbtInformation.physicalLoadcarrierId) &&
        Objects.equals(this.loadcarrierExternalId, rbtInformation.loadcarrierExternalId) &&
        Objects.equals(this.flexField, rbtInformation.flexField) &&
        Objects.equals(this.combinationTripId, rbtInformation.combinationTripId) &&
        Objects.equals(this.telephoneNumber, rbtInformation.telephoneNumber) &&
        Objects.equals(this.tmsOperationId, rbtInformation.tmsOperationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routeId, tripId, stopId, planId, areaId, locationId, driverId, truckId, logicalLoadcarrierId, physicalLoadcarrierId, loadcarrierExternalId, flexField, combinationTripId, telephoneNumber, tmsOperationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RbtInformation {\n");
    sb.append("    routeId: ").append(toIndentedString(routeId)).append("\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    stopId: ").append(toIndentedString(stopId)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    areaId: ").append(toIndentedString(areaId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    driverId: ").append(toIndentedString(driverId)).append("\n");
    sb.append("    truckId: ").append(toIndentedString(truckId)).append("\n");
    sb.append("    logicalLoadcarrierId: ").append(toIndentedString(logicalLoadcarrierId)).append("\n");
    sb.append("    physicalLoadcarrierId: ").append(toIndentedString(physicalLoadcarrierId)).append("\n");
    sb.append("    loadcarrierExternalId: ").append(toIndentedString(loadcarrierExternalId)).append("\n");
    sb.append("    flexField: ").append(toIndentedString(flexField)).append("\n");
    sb.append("    combinationTripId: ").append(toIndentedString(combinationTripId)).append("\n");
    sb.append("    telephoneNumber: ").append(toIndentedString(telephoneNumber)).append("\n");
    sb.append("    tmsOperationId: ").append(toIndentedString(tmsOperationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

