/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TrackingRecipients
 */
@JsonPropertyOrder({
  TrackingRecipients.JSON_PROPERTY_IDENT,
  TrackingRecipients.JSON_PROPERTY_ACTOR_NO,
  TrackingRecipients.JSON_PROPERTY_TYPE
})
@JsonTypeName("trackingRecipients")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class TrackingRecipients {
  public static final String JSON_PROPERTY_IDENT = "ident";
  private String ident;

  public static final String JSON_PROPERTY_ACTOR_NO = "actorNo";
  private String actorNo;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;


  public TrackingRecipients ident(String ident) {
    
    this.ident = ident;
    return this;
  }

   /**
   * Get ident
   * @return ident
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IDENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdent() {
    return ident;
  }


  public void setIdent(String ident) {
    this.ident = ident;
  }


  public TrackingRecipients actorNo(String actorNo) {
    
    this.actorNo = actorNo;
    return this;
  }

   /**
   * Get actorNo
   * @return actorNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTOR_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getActorNo() {
    return actorNo;
  }


  public void setActorNo(String actorNo) {
    this.actorNo = actorNo;
  }


  public TrackingRecipients type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackingRecipients trackingRecipients = (TrackingRecipients) o;
    return Objects.equals(this.ident, trackingRecipients.ident) &&
        Objects.equals(this.actorNo, trackingRecipients.actorNo) &&
        Objects.equals(this.type, trackingRecipients.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ident, actorNo, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackingRecipients {\n");
    sb.append("    ident: ").append(toIndentedString(ident)).append("\n");
    sb.append("    actorNo: ").append(toIndentedString(actorNo)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

