/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * WeightVolTemp
 */
@JsonPropertyOrder({
  WeightVolTemp.JSON_PROPERTY_WEIGHT,
  WeightVolTemp.JSON_PROPERTY_HEIGHT,
  WeightVolTemp.JSON_PROPERTY_LENGTH,
  WeightVolTemp.JSON_PROPERTY_BREADTH,
  WeightVolTemp.JSON_PROPERTY_TEMPERATURE,
  WeightVolTemp.JSON_PROPERTY_TEMPERATURE_ZONE,
  WeightVolTemp.JSON_PROPERTY_TEMPERATURE_UNIT,
  WeightVolTemp.JSON_PROPERTY_ENVIRONMENT_ID,
  WeightVolTemp.JSON_PROPERTY_TIMESTAMP,
  WeightVolTemp.JSON_PROPERTY_TIMESTAMP_TYPE
})
@JsonTypeName("weightVolTemp")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T14:59:14.427251100+05:30[Asia/Calcutta]")
public class WeightVolTemp {
  public static final String JSON_PROPERTY_WEIGHT = "weight";
  private BigDecimal weight;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private BigDecimal height;

  public static final String JSON_PROPERTY_LENGTH = "length";
  private BigDecimal length;

  public static final String JSON_PROPERTY_BREADTH = "breadth";
  private BigDecimal breadth;

  public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
  private BigDecimal temperature;

  public static final String JSON_PROPERTY_TEMPERATURE_ZONE = "temperatureZone";
  private String temperatureZone;

  public static final String JSON_PROPERTY_TEMPERATURE_UNIT = "temperatureUnit";
  private String temperatureUnit;

  public static final String JSON_PROPERTY_ENVIRONMENT_ID = "environmentId";
  private String environmentId;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private String timestamp;

  public static final String JSON_PROPERTY_TIMESTAMP_TYPE = "timestampType";
  private String timestampType;


  public WeightVolTemp weight(BigDecimal weight) {
    
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getWeight() {
    return weight;
  }


  public void setWeight(BigDecimal weight) {
    this.weight = weight;
  }


  public WeightVolTemp height(BigDecimal height) {
    
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getHeight() {
    return height;
  }


  public void setHeight(BigDecimal height) {
    this.height = height;
  }


  public WeightVolTemp length(BigDecimal length) {
    
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLength() {
    return length;
  }


  public void setLength(BigDecimal length) {
    this.length = length;
  }


  public WeightVolTemp breadth(BigDecimal breadth) {
    
    this.breadth = breadth;
    return this;
  }

   /**
   * Get breadth
   * @return breadth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BREADTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getBreadth() {
    return breadth;
  }


  public void setBreadth(BigDecimal breadth) {
    this.breadth = breadth;
  }


  public WeightVolTemp temperature(BigDecimal temperature) {
    
    this.temperature = temperature;
    return this;
  }

   /**
   * Get temperature
   * @return temperature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEMPERATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTemperature() {
    return temperature;
  }


  public void setTemperature(BigDecimal temperature) {
    this.temperature = temperature;
  }


  public WeightVolTemp temperatureZone(String temperatureZone) {
    
    this.temperatureZone = temperatureZone;
    return this;
  }

   /**
   * Get temperatureZone
   * @return temperatureZone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEMPERATURE_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTemperatureZone() {
    return temperatureZone;
  }


  public void setTemperatureZone(String temperatureZone) {
    this.temperatureZone = temperatureZone;
  }


  public WeightVolTemp temperatureUnit(String temperatureUnit) {
    
    this.temperatureUnit = temperatureUnit;
    return this;
  }

   /**
   * Get temperatureUnit
   * @return temperatureUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEMPERATURE_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTemperatureUnit() {
    return temperatureUnit;
  }


  public void setTemperatureUnit(String temperatureUnit) {
    this.temperatureUnit = temperatureUnit;
  }


  public WeightVolTemp environmentId(String environmentId) {
    
    this.environmentId = environmentId;
    return this;
  }

   /**
   * Get environmentId
   * @return environmentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENVIRONMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEnvironmentId() {
    return environmentId;
  }


  public void setEnvironmentId(String environmentId) {
    this.environmentId = environmentId;
  }


  public WeightVolTemp timestamp(String timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }


  public WeightVolTemp timestampType(String timestampType) {
    
    this.timestampType = timestampType;
    return this;
  }

   /**
   * Get timestampType
   * @return timestampType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestampType() {
    return timestampType;
  }


  public void setTimestampType(String timestampType) {
    this.timestampType = timestampType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeightVolTemp weightVolTemp = (WeightVolTemp) o;
    return Objects.equals(this.weight, weightVolTemp.weight) &&
        Objects.equals(this.height, weightVolTemp.height) &&
        Objects.equals(this.length, weightVolTemp.length) &&
        Objects.equals(this.breadth, weightVolTemp.breadth) &&
        Objects.equals(this.temperature, weightVolTemp.temperature) &&
        Objects.equals(this.temperatureZone, weightVolTemp.temperatureZone) &&
        Objects.equals(this.temperatureUnit, weightVolTemp.temperatureUnit) &&
        Objects.equals(this.environmentId, weightVolTemp.environmentId) &&
        Objects.equals(this.timestamp, weightVolTemp.timestamp) &&
        Objects.equals(this.timestampType, weightVolTemp.timestampType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weight, height, length, breadth, temperature, temperatureZone, temperatureUnit, environmentId, timestamp, timestampType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeightVolTemp {\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    breadth: ").append(toIndentedString(breadth)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    temperatureZone: ").append(toIndentedString(temperatureZone)).append("\n");
    sb.append("    temperatureUnit: ").append(toIndentedString(temperatureUnit)).append("\n");
    sb.append("    environmentId: ").append(toIndentedString(environmentId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    timestampType: ").append(toIndentedString(timestampType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

