/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Attributes
 */
public class AttributesTest {
    private final Attributes model = new Attributes();

    /**
     * Model tests for Attributes
     */
    @Test
    public void testAttributes() {
        // TODO: test Attributes
    }

    /**
     * Test the property 'actorNoSource'
     */
    @Test
    public void actorNoSourceTest() {
        // TODO: test actorNoSource
    }

    /**
     * Test the property 'eventCodeSource'
     */
    @Test
    public void eventCodeSourceTest() {
        // TODO: test eventCodeSource
    }

    /**
     * Test the property 'actionCodeSource'
     */
    @Test
    public void actionCodeSourceTest() {
        // TODO: test actionCodeSource
    }

    /**
     * Test the property 'reasonCodeSource'
     */
    @Test
    public void reasonCodeSourceTest() {
        // TODO: test reasonCodeSource
    }

    /**
     * Test the property 'eventSource'
     */
    @Test
    public void eventSourceTest() {
        // TODO: test eventSource
    }

    /**
     * Test the property 'statusMassRegistration'
     */
    @Test
    public void statusMassRegistrationTest() {
        // TODO: test statusMassRegistration
    }

    /**
     * Test the property 'timestampUTC'
     */
    @Test
    public void timestampUTCTest() {
        // TODO: test timestampUTC
    }

    /**
     * Test the property 'timezoneUTC'
     */
    @Test
    public void timezoneUTCTest() {
        // TODO: test timezoneUTC
    }

    /**
     * Test the property 'totalRegistered'
     */
    @Test
    public void totalRegisteredTest() {
        // TODO: test totalRegistered
    }

    /**
     * Test the property 'volumeRegistered'
     */
    @Test
    public void volumeRegisteredTest() {
        // TODO: test volumeRegistered
    }

    /**
     * Test the property 'amountPaid'
     */
    @Test
    public void amountPaidTest() {
        // TODO: test amountPaid
    }

    /**
     * Test the property 'chargeId'
     */
    @Test
    public void chargeIdTest() {
        // TODO: test chargeId
    }

    /**
     * Test the property 'emsStatus'
     */
    @Test
    public void emsStatusTest() {
        // TODO: test emsStatus
    }

    /**
     * Test the property 'fullMaktCode'
     */
    @Test
    public void fullMaktCodeTest() {
        // TODO: test fullMaktCode
    }

    /**
     * Test the property 'damageTypeCode'
     */
    @Test
    public void damageTypeCodeTest() {
        // TODO: test damageTypeCode
    }

}
