/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AuditLog
 */
public class AuditLogTest {
    private final AuditLog model = new AuditLog();

    /**
     * Model tests for AuditLog
     */
    @Test
    public void testAuditLog() {
        // TODO: test AuditLog
    }

    /**
     * Test the property 'weekNumber'
     */
    @Test
    public void weekNumberTest() {
        // TODO: test weekNumber
    }

    /**
     * Test the property 'modifiedProgramId'
     */
    @Test
    public void modifiedProgramIdTest() {
        // TODO: test modifiedProgramId
    }

    /**
     * Test the property 'modifiedTimestamp'
     */
    @Test
    public void modifiedTimestampTest() {
        // TODO: test modifiedTimestamp
    }

    /**
     * Test the property 'modifiedCompanyCode'
     */
    @Test
    public void modifiedCompanyCodeTest() {
        // TODO: test modifiedCompanyCode
    }

    /**
     * Test the property 'modifiedUserId'
     */
    @Test
    public void modifiedUserIdTest() {
        // TODO: test modifiedUserId
    }

    /**
     * Test the property 'createdProgramId'
     */
    @Test
    public void createdProgramIdTest() {
        // TODO: test createdProgramId
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'createdCompanyCode'
     */
    @Test
    public void createdCompanyCodeTest() {
        // TODO: test createdCompanyCode
    }

    /**
     * Test the property 'createdUserId'
     */
    @Test
    public void createdUserIdTest() {
        // TODO: test createdUserId
    }

    /**
     * Test the property 'messageId'
     */
    @Test
    public void messageIdTest() {
        // TODO: test messageId
    }

}
