/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CashOnDelivery
 */
public class CashOnDeliveryTest {
    private final CashOnDelivery model = new CashOnDelivery();

    /**
     * Model tests for CashOnDelivery
     */
    @Test
    public void testCashOnDelivery() {
        // TODO: test CashOnDelivery
    }

    /**
     * Test the property 'goodsDescription'
     */
    @Test
    public void goodsDescriptionTest() {
        // TODO: test goodsDescription
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'amountCurrency'
     */
    @Test
    public void amountCurrencyTest() {
        // TODO: test amountCurrency
    }

    /**
     * Test the property 'controlIdentificationNumber'
     */
    @Test
    public void controlIdentificationNumberTest() {
        // TODO: test controlIdentificationNumber
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'amountCheckDigit'
     */
    @Test
    public void amountCheckDigitTest() {
        // TODO: test amountCheckDigit
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'createdProgramId'
     */
    @Test
    public void createdProgramIdTest() {
        // TODO: test createdProgramId
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'modifiedProgramId'
     */
    @Test
    public void modifiedProgramIdTest() {
        // TODO: test modifiedProgramId
    }

    /**
     * Test the property 'modifiedTimestamp'
     */
    @Test
    public void modifiedTimestampTest() {
        // TODO: test modifiedTimestamp
    }

}
