/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Charges
 */
public class ChargesTest {
    private final Charges model = new Charges();

    /**
     * Model tests for Charges
     */
    @Test
    public void testCharges() {
        // TODO: test Charges
    }

    /**
     * Test the property 'chargeType'
     */
    @Test
    public void chargeTypeTest() {
        // TODO: test chargeType
    }

    /**
     * Test the property 'chargeCode'
     */
    @Test
    public void chargeCodeTest() {
        // TODO: test chargeCode
    }

    /**
     * Test the property 'netAmount'
     */
    @Test
    public void netAmountTest() {
        // TODO: test netAmount
    }

    /**
     * Test the property 'netCurrency'
     */
    @Test
    public void netCurrencyTest() {
        // TODO: test netCurrency
    }

    /**
     * Test the property 'grossAmount'
     */
    @Test
    public void grossAmountTest() {
        // TODO: test grossAmount
    }

    /**
     * Test the property 'grossCurrency'
     */
    @Test
    public void grossCurrencyTest() {
        // TODO: test grossCurrency
    }

}
