/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import no.posten.ph.consignment.model.Attributes;
import no.posten.ph.consignment.model.AuditLog;
import no.posten.ph.consignment.model.Coordinates;
import no.posten.ph.consignment.model.DeliveryDetails;
import no.posten.ph.consignment.model.Images;
import no.posten.ph.consignment.model.RbtInformation;
import no.posten.ph.consignment.model.Signature;
import no.posten.ph.consignment.model.WeightVolTemp;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConsignmentEvent
 */
public class ConsignmentEventTest {
    private final ConsignmentEvent model = new ConsignmentEvent();

    /**
     * Model tests for ConsignmentEvent
     */
    @Test
    public void testConsignmentEvent() {
        // TODO: test ConsignmentEvent
    }

    /**
     * Test the property 'consignmentNo'
     */
    @Test
    public void consignmentNoTest() {
        // TODO: test consignmentNo
    }

    /**
     * Test the property 'eventDate'
     */
    @Test
    public void eventDateTest() {
        // TODO: test eventDate
    }

    /**
     * Test the property 'eventTime'
     */
    @Test
    public void eventTimeTest() {
        // TODO: test eventTime
    }

    /**
     * Test the property 'eventCode'
     */
    @Test
    public void eventCodeTest() {
        // TODO: test eventCode
    }

    /**
     * Test the property 'actionCode'
     */
    @Test
    public void actionCodeTest() {
        // TODO: test actionCode
    }

    /**
     * Test the property 'reasonCode'
     */
    @Test
    public void reasonCodeTest() {
        // TODO: test reasonCode
    }

    /**
     * Test the property 'unitCode'
     */
    @Test
    public void unitCodeTest() {
        // TODO: test unitCode
    }

    /**
     * Test the property 'postCode'
     */
    @Test
    public void postCodeTest() {
        // TODO: test postCode
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'companyCode'
     */
    @Test
    public void companyCodeTest() {
        // TODO: test companyCode
    }

    /**
     * Test the property 'consignmentNoSource'
     */
    @Test
    public void consignmentNoSourceTest() {
        // TODO: test consignmentNoSource
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'systemCode'
     */
    @Test
    public void systemCodeTest() {
        // TODO: test systemCode
    }

    /**
     * Test the property 'sourceSystem'
     */
    @Test
    public void sourceSystemTest() {
        // TODO: test sourceSystem
    }

    /**
     * Test the property 'equipmentType'
     */
    @Test
    public void equipmentTypeTest() {
        // TODO: test equipmentType
    }

    /**
     * Test the property 'equipmentId'
     */
    @Test
    public void equipmentIdTest() {
        // TODO: test equipmentId
    }

    /**
     * Test the property 'equipmentMsgCounter'
     */
    @Test
    public void equipmentMsgCounterTest() {
        // TODO: test equipmentMsgCounter
    }

    /**
     * Test the property 'postReference'
     */
    @Test
    public void postReferenceTest() {
        // TODO: test postReference
    }

    /**
     * Test the property 'handedOverToUnit'
     */
    @Test
    public void handedOverToUnitTest() {
        // TODO: test handedOverToUnit
    }

    /**
     * Test the property 'shelfCode'
     */
    @Test
    public void shelfCodeTest() {
        // TODO: test shelfCode
    }

    /**
     * Test the property 'pickUpCode'
     */
    @Test
    public void pickUpCodeTest() {
        // TODO: test pickUpCode
    }

    /**
     * Test the property 'returnDate'
     */
    @Test
    public void returnDateTest() {
        // TODO: test returnDate
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'deliveryDetails'
     */
    @Test
    public void deliveryDetailsTest() {
        // TODO: test deliveryDetails
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'rbtInformation'
     */
    @Test
    public void rbtInformationTest() {
        // TODO: test rbtInformation
    }

    /**
     * Test the property 'coordinates'
     */
    @Test
    public void coordinatesTest() {
        // TODO: test coordinates
    }

    /**
     * Test the property 'weightVolTemp'
     */
    @Test
    public void weightVolTempTest() {
        // TODO: test weightVolTemp
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'auditLog'
     */
    @Test
    public void auditLogTest() {
        // TODO: test auditLog
    }

}
