/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import no.posten.ph.consignment.model.AuditLog;
import no.posten.ph.consignment.model.CashOnDelivery;
import no.posten.ph.consignment.model.Charges;
import no.posten.ph.consignment.model.ConsignmentEvent;
import no.posten.ph.consignment.model.DangerousGoods;
import no.posten.ph.consignment.model.DateAndTime;
import no.posten.ph.consignment.model.Equipment;
import no.posten.ph.consignment.model.FreeText;
import no.posten.ph.consignment.model.Insurance;
import no.posten.ph.consignment.model.Party;
import no.posten.ph.consignment.model.PartyConsignee;
import no.posten.ph.consignment.model.PartyConsignor;
import no.posten.ph.consignment.model.Reference;
import no.posten.ph.consignment.model.TrackingRecipients;
import no.posten.ph.consignment.model.Vas;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Consignment
 */
public class ConsignmentTest {
    private final Consignment model = new Consignment();

    /**
     * Model tests for Consignment
     */
    @Test
    public void testConsignment() {
        // TODO: test Consignment
    }

    /**
     * Test the property 'consignmentNo'
     */
    @Test
    public void consignmentNoTest() {
        // TODO: test consignmentNo
    }

    /**
     * Test the property 'consignmentNoType'
     */
    @Test
    public void consignmentNoTypeTest() {
        // TODO: test consignmentNoType
    }

    /**
     * Test the property 'consignmentNoIdentifier'
     */
    @Test
    public void consignmentNoIdentifierTest() {
        // TODO: test consignmentNoIdentifier
    }

    /**
     * Test the property 'consignmentNoIssuer'
     */
    @Test
    public void consignmentNoIssuerTest() {
        // TODO: test consignmentNoIssuer
    }

    /**
     * Test the property 'consignmentMaster'
     */
    @Test
    public void consignmentMasterTest() {
        // TODO: test consignmentMaster
    }

    /**
     * Test the property 'productCode'
     */
    @Test
    public void productCodeTest() {
        // TODO: test productCode
    }

    /**
     * Test the property 'serviceGroup'
     */
    @Test
    public void serviceGroupTest() {
        // TODO: test serviceGroup
    }

    /**
     * Test the property 'termsOfDeliver'
     */
    @Test
    public void termsOfDeliverTest() {
        // TODO: test termsOfDeliver
    }

    /**
     * Test the property 'numberOfPackages'
     */
    @Test
    public void numberOfPackagesTest() {
        // TODO: test numberOfPackages
    }

    /**
     * Test the property 'netWeight'
     */
    @Test
    public void netWeightTest() {
        // TODO: test netWeight
    }

    /**
     * Test the property 'grossWeight'
     */
    @Test
    public void grossWeightTest() {
        // TODO: test grossWeight
    }

    /**
     * Test the property 'grossVolume'
     */
    @Test
    public void grossVolumeTest() {
        // TODO: test grossVolume
    }

    /**
     * Test the property 'loadingMetres'
     */
    @Test
    public void loadingMetresTest() {
        // TODO: test loadingMetres
    }

    /**
     * Test the property 'palletFootprints'
     */
    @Test
    public void palletFootprintsTest() {
        // TODO: test palletFootprints
    }

    /**
     * Test the property 'goodsDescription'
     */
    @Test
    public void goodsDescriptionTest() {
        // TODO: test goodsDescription
    }

    /**
     * Test the property 'dgsTotalPoints'
     */
    @Test
    public void dgsTotalPointsTest() {
        // TODO: test dgsTotalPoints
    }

    /**
     * Test the property 'termsType'
     */
    @Test
    public void termsTypeTest() {
        // TODO: test termsType
    }

    /**
     * Test the property 'termsCode'
     */
    @Test
    public void termsCodeTest() {
        // TODO: test termsCode
    }

    /**
     * Test the property 'termsLocation'
     */
    @Test
    public void termsLocationTest() {
        // TODO: test termsLocation
    }

    /**
     * Test the property 'temperatureTransportMin'
     */
    @Test
    public void temperatureTransportMinTest() {
        // TODO: test temperatureTransportMin
    }

    /**
     * Test the property 'temperatureTransportMax'
     */
    @Test
    public void temperatureTransportMaxTest() {
        // TODO: test temperatureTransportMax
    }

    /**
     * Test the property 'temperatureStorageMin'
     */
    @Test
    public void temperatureStorageMinTest() {
        // TODO: test temperatureStorageMin
    }

    /**
     * Test the property 'temperatureStorageMax'
     */
    @Test
    public void temperatureStorageMaxTest() {
        // TODO: test temperatureStorageMax
    }

    /**
     * Test the property 'agreedDiscount'
     */
    @Test
    public void agreedDiscountTest() {
        // TODO: test agreedDiscount
    }

    /**
     * Test the property 'orderType'
     */
    @Test
    public void orderTypeTest() {
        // TODO: test orderType
    }

    /**
     * Test the property 'discountRegisteredBy'
     */
    @Test
    public void discountRegisteredByTest() {
        // TODO: test discountRegisteredBy
    }

    /**
     * Test the property 'bookingReference'
     */
    @Test
    public void bookingReferenceTest() {
        // TODO: test bookingReference
    }

    /**
     * Test the property 'syntheticStatus'
     */
    @Test
    public void syntheticStatusTest() {
        // TODO: test syntheticStatus
    }

    /**
     * Test the property 'receiverReference'
     */
    @Test
    public void receiverReferenceTest() {
        // TODO: test receiverReference
    }

    /**
     * Test the property 'vas'
     */
    @Test
    public void vasTest() {
        // TODO: test vas
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'freeText'
     */
    @Test
    public void freeTextTest() {
        // TODO: test freeText
    }

    /**
     * Test the property 'dateTime'
     */
    @Test
    public void dateTimeTest() {
        // TODO: test dateTime
    }

    /**
     * Test the property 'trackingRecipients'
     */
    @Test
    public void trackingRecipientsTest() {
        // TODO: test trackingRecipients
    }

    /**
     * Test the property 'partyConsignor'
     */
    @Test
    public void partyConsignorTest() {
        // TODO: test partyConsignor
    }

    /**
     * Test the property 'partyConsignee'
     */
    @Test
    public void partyConsigneeTest() {
        // TODO: test partyConsignee
    }

    /**
     * Test the property 'party'
     */
    @Test
    public void partyTest() {
        // TODO: test party
    }

    /**
     * Test the property 'dangerousGoods'
     */
    @Test
    public void dangerousGoodsTest() {
        // TODO: test dangerousGoods
    }

    /**
     * Test the property 'cashOnDelivery'
     */
    @Test
    public void cashOnDeliveryTest() {
        // TODO: test cashOnDelivery
    }

    /**
     * Test the property 'charges'
     */
    @Test
    public void chargesTest() {
        // TODO: test charges
    }

    /**
     * Test the property 'insurance'
     */
    @Test
    public void insuranceTest() {
        // TODO: test insurance
    }

    /**
     * Test the property 'equipment'
     */
    @Test
    public void equipmentTest() {
        // TODO: test equipment
    }

    /**
     * Test the property 'auditLog'
     */
    @Test
    public void auditLogTest() {
        // TODO: test auditLog
    }

    /**
     * Test the property 'consignmentEvent'
     */
    @Test
    public void consignmentEventTest() {
        // TODO: test consignmentEvent
    }

}
