/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Coordinates
 */
public class CoordinatesTest {
    private final Coordinates model = new Coordinates();

    /**
     * Model tests for Coordinates
     */
    @Test
    public void testCoordinates() {
        // TODO: test Coordinates
    }

    /**
     * Test the property 'xCoordinate'
     */
    @Test
    public void xCoordinateTest() {
        // TODO: test xCoordinate
    }

    /**
     * Test the property 'yCoordinate'
     */
    @Test
    public void yCoordinateTest() {
        // TODO: test yCoordinate
    }

    /**
     * Test the property 'coordinateSystem'
     */
    @Test
    public void coordinateSystemTest() {
        // TODO: test coordinateSystem
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

}
