/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DangerousGoods
 */
public class DangerousGoodsTest {
    private final DangerousGoods model = new DangerousGoods();

    /**
     * Model tests for DangerousGoods
     */
    @Test
    public void testDangerousGoods() {
        // TODO: test DangerousGoods
    }

    /**
     * Test the property 'regulationCode'
     */
    @Test
    public void regulationCodeTest() {
        // TODO: test regulationCode
    }

    /**
     * Test the property 'hazardCode'
     */
    @Test
    public void hazardCodeTest() {
        // TODO: test hazardCode
    }

    /**
     * Test the property 'additionalHazardCode'
     */
    @Test
    public void additionalHazardCodeTest() {
        // TODO: test additionalHazardCode
    }

    /**
     * Test the property 'unNo'
     */
    @Test
    public void unNoTest() {
        // TODO: test unNo
    }

    /**
     * Test the property 'packaging'
     */
    @Test
    public void packagingTest() {
        // TODO: test packaging
    }

    /**
     * Test the property 'tunnelRestrictions'
     */
    @Test
    public void tunnelRestrictionsTest() {
        // TODO: test tunnelRestrictions
    }

    /**
     * Test the property 'techName'
     */
    @Test
    public void techNameTest() {
        // TODO: test techName
    }

    /**
     * Test the property 'netWeightKg'
     */
    @Test
    public void netWeightKgTest() {
        // TODO: test netWeightKg
    }

    /**
     * Test the property 'netVolumeLitre'
     */
    @Test
    public void netVolumeLitreTest() {
        // TODO: test netVolumeLitre
    }

    /**
     * Test the property 'hazardousGoodsPoints'
     */
    @Test
    public void hazardousGoodsPointsTest() {
        // TODO: test hazardousGoodsPoints
    }

}
