/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeliveryDetails
 */
public class DeliveryDetailsTest {
    private final DeliveryDetails model = new DeliveryDetails();

    /**
     * Model tests for DeliveryDetails
     */
    @Test
    public void testDeliveryDetails() {
        // TODO: test DeliveryDetails
    }

    /**
     * Test the property 'legitimationIdType'
     */
    @Test
    public void legitimationIdTypeTest() {
        // TODO: test legitimationIdType
    }

    /**
     * Test the property 'legitimationId'
     */
    @Test
    public void legitimationIdTest() {
        // TODO: test legitimationId
    }

    /**
     * Test the property 'deliveredById'
     */
    @Test
    public void deliveredByIdTest() {
        // TODO: test deliveredById
    }

}
