/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Equipment
 */
public class EquipmentTest {
    private final Equipment model = new Equipment();

    /**
     * Model tests for Equipment
     */
    @Test
    public void testEquipment() {
        // TODO: test Equipment
    }

    /**
     * Test the property 'equipmentType'
     */
    @Test
    public void equipmentTypeTest() {
        // TODO: test equipmentType
    }

    /**
     * Test the property 'equipmentQuantity'
     */
    @Test
    public void equipmentQuantityTest() {
        // TODO: test equipmentQuantity
    }

}
