/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Insurance
 */
public class InsuranceTest {
    private final Insurance model = new Insurance();

    /**
     * Model tests for Insurance
     */
    @Test
    public void testInsurance() {
        // TODO: test Insurance
    }

    /**
     * Test the property 'goodsDescription'
     */
    @Test
    public void goodsDescriptionTest() {
        // TODO: test goodsDescription
    }

    /**
     * Test the property 'insuredAmount'
     */
    @Test
    public void insuredAmountTest() {
        // TODO: test insuredAmount
    }

    /**
     * Test the property 'insuredAmountCurrency'
     */
    @Test
    public void insuredAmountCurrencyTest() {
        // TODO: test insuredAmountCurrency
    }

}
