/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import no.posten.ph.consignment.model.DeliveryAddress;
import no.posten.ph.consignment.model.PostalAddress;
import no.posten.ph.consignment.model.Reference;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PartyConsignee
 */
public class PartyConsigneeTest {
    private final PartyConsignee model = new PartyConsignee();

    /**
     * Model tests for PartyConsignee
     */
    @Test
    public void testPartyConsignee() {
        // TODO: test PartyConsignee
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'soundexName'
     */
    @Test
    public void soundexNameTest() {
        // TODO: test soundexName
    }

    /**
     * Test the property 'actorNo'
     */
    @Test
    public void actorNoTest() {
        // TODO: test actorNo
    }

    /**
     * Test the property 'system'
     */
    @Test
    public void systemTest() {
        // TODO: test system
    }

    /**
     * Test the property 'partyId'
     */
    @Test
    public void partyIdTest() {
        // TODO: test partyId
    }

    /**
     * Test the property 'subpartyId'
     */
    @Test
    public void subpartyIdTest() {
        // TODO: test subpartyId
    }

    /**
     * Test the property 'idCodeList'
     */
    @Test
    public void idCodeListTest() {
        // TODO: test idCodeList
    }

    /**
     * Test the property 'function'
     */
    @Test
    public void functionTest() {
        // TODO: test function
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'mobile'
     */
    @Test
    public void mobileTest() {
        // TODO: test mobile
    }

    /**
     * Test the property 'telefax'
     */
    @Test
    public void telefaxTest() {
        // TODO: test telefax
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'digipostId'
     */
    @Test
    public void digipostIdTest() {
        // TODO: test digipostId
    }

    /**
     * Test the property 'personalAlias'
     */
    @Test
    public void personalAliasTest() {
        // TODO: test personalAlias
    }

    /**
     * Test the property 'createdProgramId'
     */
    @Test
    public void createdProgramIdTest() {
        // TODO: test createdProgramId
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'modifiedProgramId'
     */
    @Test
    public void modifiedProgramIdTest() {
        // TODO: test modifiedProgramId
    }

    /**
     * Test the property 'modifiedTimestamp'
     */
    @Test
    public void modifiedTimestampTest() {
        // TODO: test modifiedTimestamp
    }

    /**
     * Test the property 'postalAddress'
     */
    @Test
    public void postalAddressTest() {
        // TODO: test postalAddress
    }

    /**
     * Test the property 'deliveryAddress'
     */
    @Test
    public void deliveryAddressTest() {
        // TODO: test deliveryAddress
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

}
