/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RbtInformation
 */
public class RbtInformationTest {
    private final RbtInformation model = new RbtInformation();

    /**
     * Model tests for RbtInformation
     */
    @Test
    public void testRbtInformation() {
        // TODO: test RbtInformation
    }

    /**
     * Test the property 'routeId'
     */
    @Test
    public void routeIdTest() {
        // TODO: test routeId
    }

    /**
     * Test the property 'tripId'
     */
    @Test
    public void tripIdTest() {
        // TODO: test tripId
    }

    /**
     * Test the property 'stopId'
     */
    @Test
    public void stopIdTest() {
        // TODO: test stopId
    }

    /**
     * Test the property 'planId'
     */
    @Test
    public void planIdTest() {
        // TODO: test planId
    }

    /**
     * Test the property 'areaId'
     */
    @Test
    public void areaIdTest() {
        // TODO: test areaId
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'driverId'
     */
    @Test
    public void driverIdTest() {
        // TODO: test driverId
    }

    /**
     * Test the property 'truckId'
     */
    @Test
    public void truckIdTest() {
        // TODO: test truckId
    }

    /**
     * Test the property 'logicalLoadcarrierId'
     */
    @Test
    public void logicalLoadcarrierIdTest() {
        // TODO: test logicalLoadcarrierId
    }

    /**
     * Test the property 'physicalLoadcarrierId'
     */
    @Test
    public void physicalLoadcarrierIdTest() {
        // TODO: test physicalLoadcarrierId
    }

    /**
     * Test the property 'loadcarrierExternalId'
     */
    @Test
    public void loadcarrierExternalIdTest() {
        // TODO: test loadcarrierExternalId
    }

    /**
     * Test the property 'flexField'
     */
    @Test
    public void flexFieldTest() {
        // TODO: test flexField
    }

    /**
     * Test the property 'combinationTripId'
     */
    @Test
    public void combinationTripIdTest() {
        // TODO: test combinationTripId
    }

    /**
     * Test the property 'telephoneNumber'
     */
    @Test
    public void telephoneNumberTest() {
        // TODO: test telephoneNumber
    }

    /**
     * Test the property 'tmsOperationId'
     */
    @Test
    public void tmsOperationIdTest() {
        // TODO: test tmsOperationId
    }

}
