/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TrackingRecipients
 */
public class TrackingRecipientsTest {
    private final TrackingRecipients model = new TrackingRecipients();

    /**
     * Model tests for TrackingRecipients
     */
    @Test
    public void testTrackingRecipients() {
        // TODO: test TrackingRecipients
    }

    /**
     * Test the property 'ident'
     */
    @Test
    public void identTest() {
        // TODO: test ident
    }

    /**
     * Test the property 'actorNo'
     */
    @Test
    public void actorNoTest() {
        // TODO: test actorNo
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
