/*
 * Consignment Service
 * Consignment service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.posten.ph.consignment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Vas
 */
public class VasTest {
    private final Vas model = new Vas();

    /**
     * Model tests for Vas
     */
    @Test
    public void testVas() {
        // TODO: test Vas
    }

    /**
     * Test the property 'vasCode'
     */
    @Test
    public void vasCodeTest() {
        // TODO: test vasCode
    }

    /**
     * Test the property 'serviceRequirements'
     */
    @Test
    public void serviceRequirementsTest() {
        // TODO: test serviceRequirements
    }

    /**
     * Test the property 'discountPercent'
     */
    @Test
    public void discountPercentTest() {
        // TODO: test discountPercent
    }

    /**
     * Test the property 'createdProgramId'
     */
    @Test
    public void createdProgramIdTest() {
        // TODO: test createdProgramId
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'modifiedProgramId'
     */
    @Test
    public void modifiedProgramIdTest() {
        // TODO: test modifiedProgramId
    }

    /**
     * Test the property 'modifiedTimestamp'
     */
    @Test
    public void modifiedTimestampTest() {
        // TODO: test modifiedTimestamp
    }

}
